export type QuestLevel = 1 | 2 | 3 | 4;

export type QuestScope = 'match' | 'session' | 'cumulative';

export interface Quest {
  id: string;
  level: QuestLevel;
  target: number;
  hook: string;
  predicate?: Record<string, unknown>;
  scope: QuestScope;
  text_fr: string;
  text_en: string;
  allowSoloVSelf?: boolean;
}

export const QUESTS: Quest[] = [
  { id: 'social-friend-request-sent', level: 1, target: 1, hook: 'social.friend.request.sent', scope: 'cumulative',
    text_fr: "envoyer une demande d'ami à un joueur",
    text_en: "send a friend request to another player" },
  { id: 'social-play-friend', level: 1, target: 1, hook: 'social.match.played.friend', scope: 'cumulative',
    text_fr: "jouer contre un ami",
    text_en: "play a match against a friend" },
  { id: 'discard-10', level: 1, target: 10, hook: 'card.discarded', scope: 'cumulative',
    text_fr: "défausser 10 cartes",
    text_en: "discard 10 cards" },
  { id: 'ai-easy-play-1', level: 1, target: 1, hook: 'match.played.ai', predicate: { difficulty: 'easy' }, scope: 'cumulative',
    text_fr: "jouer une partie contre l'IA Facile",
    text_en: "play a match against the Easy AI" },
  { id: 'ui-deckbuilder-open', level: 1, target: 1, hook: 'ui.deck_builder.opened', scope: 'cumulative',
    text_fr: "ouvrir le Deck Builder",
    text_en: "open the Deck Builder" },
  { id: 'ui-leaderboard-open', level: 1, target: 1, hook: 'ui.leaderboard.opened', scope: 'cumulative',
    text_fr: "consulter le classement ELO",
    text_en: "view the ELO leaderboard" },
  { id: 'ui-profile-open', level: 1, target: 1, hook: 'ui.profile.opened', scope: 'cumulative',
    text_fr: "consulter ton profil",
    text_en: "view your profile" },
  { id: 'social-friend-accept', level: 1, target: 1, hook: 'social.friend.request.accepted', scope: 'cumulative',
    text_fr: "accepter une invitation d'ami",
    text_en: "accept a friend invite" },
  { id: 'social-chat-send', level: 1, target: 1, hook: 'social.chat.message.sent', scope: 'cumulative',
    text_fr: "envoyer un message dans le chat",
    text_en: "send a message in chat" },
  { id: 'play-5-characters-in-match', level: 1, target: 5, hook: 'character.played', scope: 'match',
    text_fr: "jouer 5 cartes Personnage en une partie",
    text_en: "play 5 character cards in one match" },
  { id: 'play-1-sound-village', level: 1, target: 1, hook: 'character.played.group', predicate: { group: 'Sound Village' }, scope: 'cumulative',
    text_fr: "jouer 1 personnage du Village du Son",
    text_en: "play 1 Sound Village character" },
  { id: 'play-1-akatsuki', level: 1, target: 1, hook: 'character.played.group', predicate: { group: 'Akatsuki' }, scope: 'cumulative',
    text_fr: "jouer 1 personnage Akatsuki",
    text_en: "play 1 Akatsuki character" },
  { id: 'play-1-sand-village', level: 1, target: 1, hook: 'character.played.group', predicate: { group: 'Sand Village' }, scope: 'cumulative',
    text_fr: "jouer 1 personnage du Village du Sable",
    text_en: "play 1 Sand Village character" },
  { id: 'play-1-sannin', level: 1, target: 1, hook: 'character.played.keyword', predicate: { keyword: 'Sannin' }, scope: 'cumulative',
    text_fr: "jouer 1 personnage Sannin",
    text_en: "play 1 Sannin character" },
  { id: 'play-1-summon', level: 1, target: 1, hook: 'character.played.keyword', predicate: { keyword: 'Summon' }, scope: 'cumulative',
    text_fr: "jouer 1 personnage Invocation",
    text_en: "play 1 Summon character" },
  { id: 'hide-1-in-match', level: 1, target: 1, hook: 'character.hidden', scope: 'match',
    text_fr: "cacher 1 personnage en une partie",
    text_en: "hide 1 character in a match" },
  { id: 'defeat-1-in-match', level: 1, target: 1, hook: 'character.defeated', scope: 'match',
    text_fr: "vaincre 1 personnage en une partie",
    text_en: "defeat 1 character in a match" },
  { id: 'move-1-in-match', level: 1, target: 1, hook: 'character.moved', scope: 'match',
    text_fr: "déplacer 1 personnage en une partie",
    text_en: "move 1 character in a match" },
  { id: 'booster-open-1', level: 1, target: 1, hook: 'booster.opened', scope: 'cumulative',
    text_fr: "ouvrir 1 booster variante",
    text_en: "open 1 variant booster" },
  { id: 'daily-quest-complete-1', level: 1, target: 1, hook: 'daily_quest.completed', scope: 'cumulative',
    text_fr: "compléter 1 quête quotidienne",
    text_en: "complete 1 daily quest" },
  { id: 'deck-share-1', level: 1, target: 1, hook: 'deck.exported', scope: 'cumulative',
    text_fr: "partager un deck (code d'export)",
    text_en: "share a deck (export code)" },
  { id: 'ui-collection-open', level: 1, target: 1, hook: 'ui.collection.opened', scope: 'cumulative',
    text_fr: "consulter la Collection",
    text_en: "view the Collection" },
  { id: 'variant-card-played-1', level: 1, target: 1, hook: 'variant.card.played', scope: 'match',
    text_fr: "jouer avec une carte variante dans une partie",
    text_en: "play with a variant card in a match" },
  { id: 'akamaru-kiba-same-mission', level: 1, target: 1, hook: 'mission.has.characters',
    predicate: { names: ['AKAMARU', 'KIBA INUZUKA'] }, scope: 'match',
    text_fr: "avoir Akamaru et Kiba sur la même mission en une partie",
    text_en: "have Akamaru and Kiba on the same mission in one match" },
  { id: 'summon-played-by-jiraya', level: 1, target: 1, hook: 'character.played.by.effect',
    predicate: { sourceName: 'JIRAYA', targetKeyword: 'Summon' }, scope: 'match',
    text_fr: "invoquer une carte Invocation grâce à Jiraya",
    text_en: "summon a Summon card thanks to Jiraya" },

  { id: 'discard-25', level: 2, target: 25, hook: 'card.discarded', scope: 'cumulative',
    text_fr: "défausser 25 cartes",
    text_en: "discard 25 cards" },
  { id: 'move-naruto-with-iruka-10', level: 2, target: 10, hook: 'character.moved.by.source',
    predicate: { sourceName: 'IRUKA UMINO', targetName: 'NARUTO UZUMAKI' }, scope: 'cumulative',
    text_fr: "déplacer Naruto avec Iruka 10 fois",
    text_en: "move Naruto with Iruka 10 times" },
  { id: 'sacrifice-gemma-3', level: 2, target: 3, hook: 'character.sacrificed.with',
    predicate: { sourceName: 'GEMMA SHIRANUI' }, scope: 'cumulative',
    text_fr: "sacrifier Gemma pour une autre carte 3 fois",
    text_en: "sacrifice Gemma for another card 3 times" },
  { id: 'hide-with-zabuza-5', level: 2, target: 5, hook: 'character.hidden.with.source',
    predicate: { sourceName: 'ZABUZA MOMOCHI' }, scope: 'cumulative',
    text_fr: "cacher 5 cartes avec Zabuza",
    text_en: "hide 5 cards with Zabuza" },
  { id: 'defeat-summon-with-manda-3', level: 2, target: 3, hook: 'character.defeated.with.source',
    predicate: { sourceName: 'MANDA', targetKeyword: 'Summon' }, scope: 'cumulative',
    text_fr: "vaincre 3 personnages Invocation avec Manda",
    text_en: "defeat 3 Summon characters with Manda" },
  { id: 'hide-with-giant-spider-3', level: 2, target: 3, hook: 'character.hidden.with.source',
    predicate: { sourceName: 'KYODAIGUMO' }, scope: 'cumulative',
    text_fr: "cacher 3 personnages avec Araignée Géante",
    text_en: "hide 3 characters with Giant Spider" },
  { id: 'neji-remove-15-tokens-match', level: 2, target: 15, hook: 'tokens.removed.with.source',
    predicate: { sourceName: 'NEJI HYÛGA' }, scope: 'match',
    text_fr: "retirer 15 jetons de Puissance avec Neji en une partie",
    text_en: "remove 15 Power tokens with Neji in one match" },
  { id: 'sasuke-ambush-5', level: 2, target: 5, hook: 'ambush.activated.with.source',
    predicate: { sourceName: 'SASUKE UCHIWA' }, scope: 'cumulative',
    text_fr: "activer l'effet AMBUSH de Sasuke 5 fois",
    text_en: "trigger Sasuke's AMBUSH effect 5 times" },
  { id: 'kiba-hide-weakest-5', level: 2, target: 5, hook: 'character.hidden.weakest.with.source',
    predicate: { sourceName: 'KIBA INUZUKA' }, scope: 'cumulative',
    text_fr: "cacher 5 fois l'ennemi le moins puissant avec Kiba",
    text_en: "hide the weakest enemy with Kiba 5 times" },
  { id: 'ebisu-draw-5', level: 2, target: 5, hook: 'card.drawn.via_effect.source',
    predicate: { sourceName: 'EBISU' }, scope: 'cumulative',
    text_fr: "piocher 5 fois grâce à Ebisu",
    text_en: "draw 5 times thanks to Ebisu" },
  { id: 'team7-same-mission', level: 2, target: 1, hook: 'mission.has.characters',
    predicate: { names: ['NARUTO UZUMAKI', 'SASUKE UCHIWA', 'SAKURA HARUNO'] }, scope: 'match',
    text_fr: "avoir Naruto, Sasuke et Sakura sur la même mission en une partie",
    text_en: "have Naruto, Sasuke and Sakura on the same mission in one match" },
  { id: 'gamabunta-with-jiraya', level: 2, target: 1, hook: 'character.played.by.effect',
    predicate: { sourceName: 'JIRAYA', targetName: 'GAMA BUNTA' }, scope: 'match',
    text_fr: "invoquer Gama Bunta avec Jiraya en une partie",
    text_en: "summon Gama Bunta with Jiraya in one match" },
  { id: 'hiruzen-reduce-cost-leaf-5', level: 2, target: 5, hook: 'cost_reduction.with.source',
    predicate: { sourceName: 'HIRUZEN SARUTOBI', targetGroup: 'Leaf Village' }, scope: 'cumulative',
    text_fr: "réduire le coût d'un personnage du Village de la Feuille avec Hiruzen 5 fois",
    text_en: "reduce a Leaf Village character's cost with Hiruzen 5 times" },
  { id: 'tenten-defeat-hidden-match', level: 2, target: 1, hook: 'character.defeated.hidden.with.source',
    predicate: { sourceName: 'TENTEN' }, scope: 'match',
    text_fr: "vaincre une carte cachée avec Tenten en une partie",
    text_en: "defeat a hidden card with Tenten in one match" },
  { id: 'asuma-ambush-3', level: 2, target: 3, hook: 'ambush.activated.with.source',
    predicate: { sourceName: 'ASUMA SARUTOBI' }, scope: 'cumulative',
    text_fr: "activer l'AMBUSH d'Asuma 3 fois",
    text_en: "trigger Asuma's AMBUSH 3 times" },
  { id: 'ai-medium-streak-3', level: 2, target: 1, hook: 'match.won.ai.streak',
    predicate: { difficulty: 'medium', streak: 3 }, scope: 'session',
    text_fr: "gagner 3 parties d'affilée contre l'IA Moyen",
    text_en: "win 3 matches in a row against the Medium AI" },
  { id: 'evolving-wins-3', level: 2, target: 3, hook: 'match.won.evolving', scope: 'cumulative',
    text_fr: "gagner 3 parties en mode Evolving",
    text_en: "win 3 matches in Evolving Mode" },
  { id: 'tokens-added-30', level: 2, target: 30, hook: 'power_token.added', scope: 'cumulative',
    text_fr: "ajouter 30 jetons de Puissance au total toutes parties confondues",
    text_en: "add 30 Power tokens across all matches" },
  { id: 'upgrade-stack-3', level: 2, target: 1, hook: 'upgrade.stack.depth',
    predicate: { depth: 3 }, scope: 'match',
    text_fr: "créer un stack d'upgrade de 3 cartes en une partie",
    text_en: "create an upgrade stack of 3 cards in one match" },
  { id: 'social-add-friends-2', level: 2, target: 2, hook: 'social.friend.added', scope: 'cumulative',
    text_fr: "ajouter 2 amis",
    text_en: "add 2 friends" },
  { id: 'daily-quests-5', level: 2, target: 5, hook: 'daily_quest.completed', scope: 'cumulative',
    text_fr: "compléter 5 quêtes quotidiennes (cumulatif)",
    text_en: "complete 5 daily quests (cumulative)" },
  { id: 'drawn-via-effect-20', level: 2, target: 20, hook: 'card.drawn.via_effect', scope: 'cumulative',
    text_fr: "piocher 20 cartes via effets toutes parties confondues",
    text_en: "draw 20 cards via effects across all matches" },
  { id: 'matches-played-25', level: 2, target: 25, hook: 'match.played', scope: 'cumulative',
    text_fr: "jouer 25 parties tous modes confondus",
    text_en: "play 25 matches across all modes" },
  { id: 'mission-A-won-1', level: 2, target: 1, hook: 'mission.won',
    predicate: { rank: 'A' }, scope: 'cumulative',
    text_fr: "gagner 1 mission de rang A",
    text_en: "win 1 rank A mission" },
  { id: 'tournament-single-won-1', level: 2, target: 1, hook: 'tournament.won.single', scope: 'cumulative',
    text_fr: "gagner 1 tournoi Single Elimination",
    text_en: "win 1 Single Elimination tournament" },

  { id: 'discard-50', level: 3, target: 50, hook: 'card.discarded', scope: 'cumulative',
    text_fr: "défausser 50 cartes",
    text_en: "discard 50 cards" },
  { id: 'neji-remove-10-tokens-match', level: 3, target: 10, hook: 'tokens.removed.with.source',
    predicate: { sourceName: 'NEJI HYÛGA' }, scope: 'match',
    text_fr: "retirer 10 jetons de Puissance avec Neji en une partie",
    text_en: "remove 10 Power tokens with Neji in one match" },
  { id: 'rock-lee-10-tokens-match', level: 3, target: 1, hook: 'character.power_tokens.threshold',
    predicate: { name: 'ROCK LEE', threshold: 10 }, scope: 'match',
    text_fr: "avoir un Rock Lee avec 10 jetons de Puissance ou plus en une partie",
    text_en: "have a Rock Lee with 10 or more Power tokens in one match" },
  { id: 'maito-gai-10-tokens-match', level: 3, target: 1, hook: 'character.power_tokens.threshold',
    predicate: { name: 'GAÏ MAITO', threshold: 10 }, scope: 'match',
    text_fr: "avoir un Maître Gai avec 10 jetons de Puissance ou plus en une partie",
    text_en: "have a Might Guy with 10 or more Power tokens in one match" },
  { id: 'draw-10-via-effects-match', level: 3, target: 10, hook: 'card.drawn.via_effect', scope: 'match',
    text_fr: "piocher 10 cartes ou plus en une partie grâce à des effets",
    text_en: "draw 10 or more cards in one match via effects" },
  { id: 'sakon-copy-5', level: 3, target: 5, hook: 'effect.copied.with.source',
    predicate: { sourceName: 'SAKON' }, scope: 'cumulative',
    text_fr: "copier 5 effets avec Sakon",
    text_en: "copy 5 effects with Sakon" },
  { id: 'ino-control-5', level: 3, target: 5, hook: 'character.controlled.with.source',
    predicate: { sourceName: 'INO YAMANAKA' }, scope: 'cumulative',
    text_fr: "prendre le contrôle de 5 personnages avec Ino",
    text_en: "take control of 5 characters with Ino" },
  { id: 'itachi-10-power-match', level: 3, target: 1, hook: 'character.power.threshold',
    predicate: { name: 'ITACHI UCHIWA', threshold: 10 }, scope: 'match',
    text_fr: "avoir un Itachi avec 10 Puissance ou plus en une partie",
    text_en: "have an Itachi with 10 or more Power in one match" },
  { id: 'temari-move-friendly-10', level: 3, target: 10, hook: 'character.moved.with.source',
    predicate: { sourceName: 'TEMARI', friendly: true }, scope: 'cumulative',
    text_fr: "déplacer 10 alliés avec Temari toutes parties confondues",
    text_en: "move 10 allies with Temari across all matches" },
  { id: 'kidomaru-defeat-5', level: 3, target: 5, hook: 'character.defeated.with.source',
    predicate: { sourceName: 'KIDÔMARU' }, scope: 'cumulative',
    text_fr: "vaincre 5 personnages avec Kidômaru toutes parties confondues",
    text_en: "defeat 5 characters with Kidômaru across all matches" },
  { id: 'kakashi-ambush-copy-5', level: 3, target: 5, hook: 'effect.copied.via_ambush.with.source',
    predicate: { sourceName: 'KAKASHI HATAKE' }, scope: 'cumulative',
    text_fr: "utiliser l'AMBUSH de Kakashi pour copier 5 effets",
    text_en: "use Kakashi's AMBUSH to copy 5 effects" },
  { id: 'defeat-kyubi', level: 3, target: 1, hook: 'character.defeated.by.name',
    predicate: { name: 'KYÛBI' }, scope: 'cumulative',
    text_fr: "vaincre un Kyûbi en jeu",
    text_en: "defeat a Kyûbi in play" },
  { id: 'kabuto-hide-5', level: 3, target: 5, hook: 'character.hidden.with.source',
    predicate: { sourceName: 'KABUTO YAKUSHI' }, scope: 'cumulative',
    text_fr: "cacher 5 personnages avec Kabuto toutes parties confondues",
    text_en: "hide 5 characters with Kabuto across all matches" },
  { id: 'reveal-for-ambush-10', level: 3, target: 10, hook: 'ambush.activated.via_reveal',
    scope: 'cumulative',
    text_fr: "révéler une carte cachée pour activer son AMBUSH 10 fois",
    text_en: "reveal a hidden card to trigger its AMBUSH 10 times" },
  { id: 'ranked-streak-5', level: 3, target: 1, hook: 'ranked.win.streak',
    predicate: { streak: 5 }, scope: 'session',
    text_fr: "gagner 5 parties d'affilée en classé",
    text_en: "win 5 ranked matches in a row" },
  { id: 'evolving-wins-10', level: 3, target: 10, hook: 'match.won.evolving', scope: 'cumulative',
    text_fr: "gagner 10 parties en mode Evolving",
    text_en: "win 10 matches in Evolving Mode" },
  { id: 'ai-expert-streak-5', level: 3, target: 1, hook: 'match.won.ai.streak',
    predicate: { difficulty: 'expert', streak: 5 }, scope: 'session',
    text_fr: "gagner 5 parties d'affilée contre l'IA Expert",
    text_en: "win 5 matches in a row against the Expert AI" },
  { id: 'elo-reach-chunin', level: 3, target: 1, hook: 'elo.tier.reached',
    predicate: { tier: 'chunin' }, scope: 'cumulative',
    text_fr: "atteindre le rang Chûnin en ELO classique",
    text_en: "reach the Chûnin rank in classic ELO" },
  { id: 'tournament-swiss-won-1', level: 3, target: 1, hook: 'tournament.won.swiss', scope: 'cumulative',
    text_fr: "gagner 1 tournoi Swiss",
    text_en: "win 1 Swiss tournament" },
  { id: 'tokens-added-50-session', level: 3, target: 50, hook: 'power_token.added', scope: 'session',
    text_fr: "ajouter 50 jetons de Puissance en une session de jeu",
    text_en: "add 50 Power tokens in one play session" },
  { id: 'hide-25-session', level: 3, target: 25, hook: 'character.hidden', scope: 'session',
    text_fr: "cacher 25 personnages en une session de jeu",
    text_en: "hide 25 characters in one play session" },
  { id: 'daily-quests-15', level: 3, target: 15, hook: 'daily_quest.completed', scope: 'cumulative',
    text_fr: "compléter 15 quêtes quotidiennes (cumulatif)",
    text_en: "complete 15 daily quests (cumulative)" },
  { id: 'mission-points-12-match', level: 3, target: 1, hook: 'mission_points.scored.match', predicate: { threshold: 12 }, scope: 'match',
    text_fr: "atteindre 12 points de mission en une seule partie",
    text_en: "reach 12 mission points in a single match" },
  { id: 'ranked-mono-sound-wins-10', level: 3, target: 10, hook: 'ranked.win.deck',
    predicate: { monoGroup: 'Sound Village' }, scope: 'cumulative',
    text_fr: "gagner 10 parties en classé avec un deck contenant uniquement des cartes du Village du Son",
    text_en: "win 10 ranked matches with a deck made only of Sound Village cards" },
  { id: 'win-without-defeats-own', level: 3, target: 1, hook: 'match.won.no_defeats_own', scope: 'cumulative',
    text_fr: "gagner une partie sans qu'aucun de tes personnages soit vaincu",
    text_en: "win a match without losing any of your characters" },

  { id: 'kisame-remove-30', level: 4, target: 30, hook: 'tokens.removed.with.source',
    predicate: { sourceName: 'KISAME HOSHIGAKI' }, scope: 'cumulative',
    text_fr: "retirer 30 jetons de Puissance avec une carte Kisame",
    text_en: "remove 30 Power tokens with a Kisame card" },
  { id: 'ranked-wins-with-ino-shika-cho-20', level: 4, target: 20, hook: 'ranked.win.deck.contains',
    predicate: { names: ['INO YAMANAKA', 'SHIKAMARU NARA', 'CHÔJI AKIMICHI'] }, scope: 'cumulative',
    text_fr: "gagner 20 parties en classé avec un deck contenant une carte Ino, une carte Shikamaru et une carte Chôji",
    text_en: "win 20 ranked matches with a deck containing an Ino card, a Shikamaru card and a Chôji card" },
  { id: 'discard-100', level: 4, target: 100, hook: 'card.discarded', scope: 'cumulative',
    text_fr: "défausser 100 cartes",
    text_en: "discard 100 cards" },
  { id: 'neji-defeat-power4-power6-same-action', level: 4, target: 1, hook: 'character.defeated.with.source.power.combo',
    predicate: { sourceName: 'NEJI HYÛGA', powers: [4, 6] }, scope: 'match',
    text_fr: "vaincre une carte de Puissance 4 et une carte de Puissance 6 avec Neji avec la même action",
    text_en: "defeat a 4 Power card and a 6 Power card with Neji in the same action" },
  { id: 'kakashi-copy-20', level: 4, target: 20, hook: 'effect.copied.with.source',
    predicate: { sourceName: 'KAKASHI HATAKE' }, scope: 'cumulative',
    text_fr: "copier 20 effets adverses avec un Kakashi",
    text_en: "copy 20 enemy effects with a Kakashi" },
  { id: 'ranked-win-no-effects-3', level: 4, target: 3, hook: 'ranked.win.no_effects_used', scope: 'cumulative',
    text_fr: "gagner 3 parties en classé sans utiliser d'effet",
    text_en: "win 3 ranked matches without using any effect" },
  { id: 'ranked-wins-50', level: 4, target: 50, hook: 'ranked.win', scope: 'cumulative',
    text_fr: "gagner 50 parties en classé",
    text_en: "win 50 ranked matches" },
  { id: 'elo-reach-hokage', level: 4, target: 1, hook: 'elo.tier.reached',
    predicate: { tier: 'will_of_fire' }, scope: 'cumulative',
    text_fr: "atteindre le rang Héritier de la Volonté du Feu en ELO classique",
    text_en: "reach the Will of Fire rank in classic ELO" },
  { id: 'ranked-streak-10', level: 4, target: 1, hook: 'ranked.win.streak',
    predicate: { streak: 10 }, scope: 'session',
    text_fr: "gagner 10 parties d'affilée en classé",
    text_en: "win 10 ranked matches in a row" },
  { id: 'evolving-wins-30', level: 4, target: 30, hook: 'match.won.evolving', scope: 'cumulative',
    text_fr: "gagner 30 parties en mode Evolving",
    text_en: "win 30 matches in Evolving Mode" },
  { id: 'tournament-swiss-won-5', level: 4, target: 5, hook: 'tournament.won.swiss', scope: 'cumulative',
    text_fr: "gagner 5 tournois Swiss",
    text_en: "win 5 Swiss tournaments" },
  { id: 'tournament-single-won-5', level: 4, target: 5, hook: 'tournament.won.single', scope: 'cumulative',
    text_fr: "gagner 5 tournois Single Elimination",
    text_en: "win 5 Single Elimination tournaments" },
  { id: 'defeat-100-cumulative', level: 4, target: 100, hook: 'character.defeated', scope: 'cumulative',
    text_fr: "vaincre 100 personnages au total",
    text_en: "defeat 100 characters in total" },
  { id: 'hide-100-cumulative', level: 4, target: 100, hook: 'character.hidden', scope: 'cumulative',
    text_fr: "cacher 100 personnages au total",
    text_en: "hide 100 characters in total" },
  { id: 'tokens-added-100', level: 4, target: 100, hook: 'power_token.added', scope: 'cumulative',
    text_fr: "ajouter 100 jetons de Puissance au total",
    text_en: "add 100 Power tokens in total" },
  { id: 'sealed-wins-10', level: 4, target: 10, hook: 'match.won.sealed', scope: 'cumulative',
    text_fr: "gagner 10 parties en scellé",
    text_en: "win 10 sealed matches" },
  { id: 'short-wins-5', level: 4, target: 5, hook: 'match.won.short',
    predicate: { maxRound: 3 }, scope: 'cumulative',
    text_fr: "gagner 5 parties en moins de 4 tours",
    text_en: "win 5 matches in fewer than 4 rounds" },
  { id: 'daily-quests-30', level: 4, target: 30, hook: 'daily_quest.completed', scope: 'cumulative',
    text_fr: "compléter 30 quêtes quotidiennes (cumulatif)",
    text_en: "complete 30 daily quests (cumulative)" },
  { id: 'boosters-opened-25', level: 4, target: 25, hook: 'booster.opened', scope: 'cumulative',
    text_fr: "ouvrir 25 boosters variantes",
    text_en: "open 25 variant boosters" },
  { id: 'tournament-mono-village-won', level: 4, target: 1, hook: 'tournament.won.mono_village', scope: 'cumulative',
    text_fr: "gagner un tournoi avec un deck mono-village",
    text_en: "win a tournament with a mono-village deck" },
  { id: 'win-deck-power-minimum-4', level: 4, target: 1, hook: 'match.won.deck.power_minimum',
    predicate: { minPrinted: 4 }, scope: 'cumulative',
    text_fr: "gagner avec un deck contenant uniquement des personnages avec 4 ou plus de Puissance imprimée",
    text_en: "win with a deck made only of characters with 4 or more printed Power" },
  { id: 'discard-200', level: 4, target: 200, hook: 'card.discarded', scope: 'cumulative',
    text_fr: "défausser 200 cartes au total",
    text_en: "discard 200 cards in total" },
  { id: 'battlepass-tier-50', level: 4, target: 1, hook: 'battlepass.tier.reached',
    predicate: { tier: 50 }, scope: 'cumulative',
    text_fr: "atteindre la Récompense de niveau 50",
    text_en: "reach Tier Reward 50" },
  { id: 'reveal-25-cumulative', level: 4, target: 25, hook: 'character.revealed', scope: 'cumulative',
    text_fr: "révéler 25 personnages cachés au total",
    text_en: "reveal 25 hidden characters in total" },
  { id: 'defeat-50-cumulative', level: 4, target: 50, hook: 'character.defeated', scope: 'cumulative',
    text_fr: "vaincre 50 personnages au total",
    text_en: "defeat 50 characters in total" },

  { id: 'trade-complete-1', level: 1, target: 1, hook: 'trade.completed', scope: 'cumulative',
    text_fr: "réaliser un échange avec un ami",
    text_en: "complete a trade with a friend" },
  { id: 'trade-complete-5', level: 2, target: 5, hook: 'trade.completed', scope: 'cumulative',
    text_fr: "réaliser 5 échanges au total",
    text_en: "complete 5 trades in total" },
  { id: 'trade-cards-10', level: 3, target: 10, hook: 'trade.cards.traded', scope: 'cumulative',
    text_fr: "échanger 10 cartes au total",
    text_en: "trade 10 cards in total" },
];

export const QUESTS_BY_ID: Record<string, Quest> = Object.fromEntries(QUESTS.map((q) => [q.id, q]));

export function getQuestById(id: string): Quest | undefined {
  return QUESTS_BY_ID[id];
}

export function getQuestsByLevel(level: QuestLevel): Quest[] {
  return QUESTS.filter((q) => q.level === level);
}

export function getQuestsByHook(hook: string): Quest[] {
  return QUESTS.filter((q) => q.hook === hook);
}
