export type QuestLevel = 1 | 2 | 3 | 4;

export type QuestScope = 'match' | 'session' | 'cumulative';

export interface Quest {
  id: string;
  level: QuestLevel;
  target: number;
  hook: string;
  predicate?: Record<string, unknown>;
  scope: QuestScope;
  text_fr: string;
  text_en: string;
  text_es?: string;
  text_ja?: string;
  text_pt?: string;
  text_it?: string;
  text_pl?: string;
  allowSoloVSelf?: boolean;
}

export const QUESTS: Quest[] = [
  { id: 'social-friend-request-sent', level: 1, target: 1, hook: 'social.friend.request.sent', scope: 'cumulative',
    text_fr: "envoyer une demande d'ami à un joueur",
    text_en: "send a friend request to another player",
    text_pt: "envie um pedido de amizade a outro jogador",
    text_it: "invia una richiesta di amicizia a un altro giocatore",
    text_pl: "wyślij zaproszenie do znajomych innemu graczowi",
    text_ja: "他のプレイヤーにフレンド申請を送る",
    text_es: "envía una solicitud de amistad a otro jugador" },
  { id: 'social-play-friend', level: 1, target: 1, hook: 'social.match.played.friend', scope: 'cumulative',
    text_fr: "jouer contre un ami",
    text_en: "play a match against a friend",
    text_pt: "jogue uma partida contra um amigo",
    text_it: "gioca una partita contro un amico",
    text_pl: "rozegraj mecz przeciwko znajomemu",
    text_ja: "フレンドと対戦する",
    text_es: "juega una partida contra un amigo" },
  { id: 'discard-10', level: 1, target: 10, hook: 'card.discarded', scope: 'cumulative',
    text_fr: "défausser 10 cartes",
    text_en: "discard 10 cards",
    text_pt: "descarte 10 cartas",
    text_it: "scarta 10 carte",
    text_pl: "odrzuć 10 kart",
    text_ja: "カードを10枚捨てる",
    text_es: "descarta 10 cartas" },
  { id: 'ai-easy-play-1', level: 1, target: 1, hook: 'match.played.ai', predicate: { difficulty: 'easy' }, scope: 'cumulative',
    text_fr: "jouer une partie contre l'IA Facile",
    text_en: "play a match against the Easy AI",
    text_pt: "jogue uma partida contra a IA Fácil",
    text_it: "gioca una partita contro l'IA Facile",
    text_pl: "rozegraj mecz przeciwko SI na poziomie Łatwym",
    text_ja: "AI（簡単）と1回対戦する",
    text_es: "juega una partida contra la IA Fácil" },
  { id: 'ui-deckbuilder-open', level: 1, target: 1, hook: 'ui.deck_builder.opened', scope: 'cumulative',
    text_fr: "ouvrir le Deck Builder",
    text_en: "open the Deck Builder",
    text_pt: "abra o Construtor de Decks",
    text_it: "apri il Costruttore di Mazzi",
    text_pl: "otwórz Kreator Talii",
    text_ja: "デッキビルダーを開く",
    text_es: "abre el Constructor de mazos" },
  { id: 'ui-leaderboard-open', level: 1, target: 1, hook: 'ui.leaderboard.opened', scope: 'cumulative',
    text_fr: "consulter le classement ELO",
    text_en: "view the ELO leaderboard",
    text_pt: "veja a classificação ELO",
    text_it: "guarda la classifica ELO",
    text_pl: "zobacz ranking ELO",
    text_ja: "ELOランキングを見る",
    text_es: "consulta la clasificación ELO" },
  { id: 'ui-profile-open', level: 1, target: 1, hook: 'ui.profile.opened', scope: 'cumulative',
    text_fr: "consulter ton profil",
    text_en: "view your profile",
    text_pt: "veja seu perfil",
    text_it: "guarda il tuo profilo",
    text_pl: "zobacz swój profil",
    text_ja: "自分のプロフィールを見る",
    text_es: "consulta tu perfil" },
  { id: 'social-friend-accept', level: 1, target: 1, hook: 'social.friend.request.accepted', scope: 'cumulative',
    text_fr: "accepter une invitation d'ami",
    text_en: "accept a friend invite",
    text_pt: "aceite um convite de amizade",
    text_it: "accetta un invito di amicizia",
    text_pl: "przyjmij zaproszenie do znajomych",
    text_ja: "フレンド申請を承認する",
    text_es: "acepta una solicitud de amistad" },
  { id: 'social-chat-send', level: 1, target: 1, hook: 'social.chat.message.sent', scope: 'cumulative',
    text_fr: "envoyer un message dans le chat",
    text_en: "send a message in chat",
    text_pt: "envie uma mensagem no chat",
    text_it: "invia un messaggio in chat",
    text_pl: "wyślij wiadomość na czacie",
    text_ja: "チャットでメッセージを送る",
    text_es: "envía un mensaje en el chat" },
  { id: 'play-5-characters-in-match', level: 1, target: 5, hook: 'character.played', scope: 'match',
    text_fr: "jouer 5 cartes Personnage en une partie",
    text_en: "play 5 character cards in one match",
    text_pt: "jogue 5 cartas personagem em uma partida",
    text_it: "gioca 5 carte personaggio in una partita",
    text_pl: "zagraj 5 kart postaci w jednym meczu",
    text_ja: "1回の対戦でキャラクターカードを5枚出す",
    text_es: "juega 5 cartas de personaje en una partida" },
  { id: 'play-1-sound-village', level: 1, target: 1, hook: 'character.played.group', predicate: { group: 'Sound Village' }, scope: 'cumulative',
    text_fr: "jouer 1 personnage du Village du Son",
    text_en: "play 1 Sound Village character",
    text_pt: "jogue 1 personagem da Vila do Som",
    text_it: "gioca 1 personaggio del Villaggio del Suono",
    text_pl: "zagraj 1 postać Wioski Dźwięku",
    text_ja: "音隠れの里のキャラクターを1体出す",
    text_es: "juega 1 personaje de la Aldea del Sonido" },
  { id: 'play-1-akatsuki', level: 1, target: 1, hook: 'character.played.group', predicate: { group: 'Akatsuki' }, scope: 'cumulative',
    text_fr: "jouer 1 personnage Akatsuki",
    text_en: "play 1 Akatsuki character",
    text_pt: "jogue 1 personagem da Akatsuki",
    text_it: "gioca 1 personaggio dell'Akatsuki",
    text_pl: "zagraj 1 postać Akatsuki",
    text_ja: "暁のキャラクターを1体出す",
    text_es: "juega 1 personaje de Akatsuki" },
  { id: 'play-1-sand-village', level: 1, target: 1, hook: 'character.played.group', predicate: { group: 'Sand Village' }, scope: 'cumulative',
    text_fr: "jouer 1 personnage du Village du Sable",
    text_en: "play 1 Sand Village character",
    text_pt: "jogue 1 personagem da Vila da Areia",
    text_it: "gioca 1 personaggio del Villaggio della Sabbia",
    text_pl: "zagraj 1 postać Wioski Piasku",
    text_ja: "砂隠れの里のキャラクターを1体出す",
    text_es: "juega 1 personaje de la Aldea de la Arena" },
  { id: 'play-1-sannin', level: 1, target: 1, hook: 'character.played.keyword', predicate: { keyword: 'Sannin' }, scope: 'cumulative',
    text_fr: "jouer 1 personnage Sannin",
    text_en: "play 1 Sannin character",
    text_pt: "jogue 1 personagem Sannin",
    text_it: "gioca 1 personaggio Sannin",
    text_pl: "zagraj 1 postać Sannin",
    text_ja: "三忍のキャラクターを1体出す",
    text_es: "juega 1 personaje Sannin" },
  { id: 'play-1-summon', level: 1, target: 1, hook: 'character.played.keyword', predicate: { keyword: 'Summon' }, scope: 'cumulative',
    text_fr: "jouer 1 personnage Invocation",
    text_en: "play 1 Summon character",
    text_pt: "jogue 1 personagem de Invocação",
    text_it: "gioca 1 personaggio Evocazione",
    text_pl: "zagraj 1 postać Przywołania",
    text_ja: "口寄せのキャラクターを1体出す",
    text_es: "juega 1 personaje de Invocación" },
  { id: 'hide-1-in-match', level: 1, target: 1, hook: 'character.hidden', scope: 'match',
    text_fr: "cacher 1 personnage en une partie",
    text_en: "hide 1 character in a match",
    text_pt: "oculte 1 personagem em uma partida",
    text_it: "nascondi 1 personaggio in una partita",
    text_pl: "ukryj 1 postać w meczu",
    text_ja: "1回の対戦でキャラクターを1体伏せる",
    text_es: "oculta 1 personaje en una partida" },
  { id: 'defeat-1-in-match', level: 1, target: 1, hook: 'character.defeated', scope: 'match',
    text_fr: "vaincre 1 personnage en une partie",
    text_en: "defeat 1 character in a match",
    text_pt: "derrote 1 personagem em uma partida",
    text_it: "sconfiggi 1 personaggio in una partita",
    text_pl: "pokonaj 1 postać w meczu",
    text_ja: "1回の対戦でキャラクターを1体撃破する",
    text_es: "derrota 1 personaje en una partida" },
  { id: 'move-1-in-match', level: 1, target: 1, hook: 'character.moved', scope: 'match',
    text_fr: "déplacer 1 personnage en une partie",
    text_en: "move 1 character in a match",
    text_pt: "mova 1 personagem em uma partida",
    text_it: "sposta 1 personaggio in una partita",
    text_pl: "przenieś 1 postać w meczu",
    text_ja: "1回の対戦でキャラクターを1体移動させる",
    text_es: "mueve 1 personaje en una partida" },
  { id: 'booster-open-1', level: 1, target: 1, hook: 'booster.opened', scope: 'cumulative',
    text_fr: "ouvrir 1 booster variante",
    text_en: "open 1 variant booster",
    text_pt: "abra 1 booster de variantes",
    text_it: "apri 1 booster di varianti",
    text_pl: "otwórz 1 booster wariantów",
    text_ja: "バリアントブースターを1個開ける",
    text_es: "abre 1 sobre de variantes" },
  { id: 'daily-quest-complete-1', level: 1, target: 1, hook: 'daily_quest.completed', scope: 'cumulative',
    text_fr: "compléter 1 quête quotidienne",
    text_en: "complete 1 daily quest",
    text_pt: "complete 1 missão diária",
    text_it: "completa 1 missione giornaliera",
    text_pl: "ukończ 1 codzienne zadanie",
    text_ja: "デイリークエストを1つ達成する",
    text_es: "completa 1 misión diaria" },
  { id: 'deck-share-1', level: 1, target: 1, hook: 'deck.exported', scope: 'cumulative',
    text_fr: "partager un deck (code d'export)",
    text_en: "share a deck (export code)",
    text_pt: "compartilhe um deck (código de exportação)",
    text_it: "condividi un mazzo (codice di esportazione)",
    text_pl: "udostępnij talię (kod eksportu)",
    text_ja: "デッキを共有する（エクスポートコード）",
    text_es: "comparte un mazo (código de exportación)" },
  { id: 'ui-collection-open', level: 1, target: 1, hook: 'ui.collection.opened', scope: 'cumulative',
    text_fr: "consulter la Collection",
    text_en: "view the Collection",
    text_pt: "veja a Coleção",
    text_it: "guarda la Collezione",
    text_pl: "zobacz Kolekcję",
    text_ja: "コレクションを見る",
    text_es: "consulta la Colección" },
  { id: 'variant-card-played-1', level: 1, target: 1, hook: 'variant.card.played', scope: 'match',
    text_fr: "jouer avec une carte variante dans une partie",
    text_en: "play with a variant card in a match",
    text_pt: "jogue com uma carta variante em uma partida",
    text_it: "gioca con una carta variante in una partita",
    text_pl: "zagraj kartą wariantową w meczu",
    text_ja: "対戦でバリアントカードを使う",
    text_es: "juega con una carta variante en una partida" },
  { id: 'akamaru-kiba-same-mission', level: 1, target: 1, hook: 'mission.has.characters',
    predicate: { names: ['AKAMARU', 'KIBA INUZUKA'] }, scope: 'match',
    text_fr: "avoir Akamaru et Kiba sur la même mission en une partie",
    text_en: "have Akamaru and Kiba on the same mission in one match",
    text_pt: "tenha Akamaru e Kiba na mesma missão em uma partida",
    text_it: "abbi Akamaru e Kiba nella stessa missione in una partita",
    text_pl: "miej Akamaru i Kibę na tej samej misji w jednym meczu",
    text_ja: "1回の対戦で赤丸と犬塚キバを同じミッションに揃える",
    text_es: "ten a Akamaru y a Kiba en la misma misión en una partida" },
  { id: 'summon-played-by-jiraya', level: 1, target: 1, hook: 'character.played.by.effect',
    predicate: { sourceName: 'JIRAYA', targetKeyword: 'Summon' }, scope: 'match',
    text_fr: "invoquer une carte Invocation grâce à Jiraya",
    text_en: "summon a Summon card thanks to Jiraya",
    text_pt: "invoque uma carta de Invocação graças a Jiraiya",
    text_it: "evoca una carta Evocazione grazie a Jiraiya",
    text_pl: "przywołaj kartę Przywołania dzięki Jiraiyi",
    text_ja: "自来也で口寄せカードを出す",
    text_es: "invoca una carta de Invocación gracias a Jiraya" },

  { id: 'discard-25', level: 2, target: 25, hook: 'card.discarded', scope: 'cumulative',
    text_fr: "défausser 25 cartes",
    text_en: "discard 25 cards",
    text_pt: "descarte 25 cartas",
    text_it: "scarta 25 carte",
    text_pl: "odrzuć 25 kart",
    text_ja: "カードを25枚捨てる",
    text_es: "descarta 25 cartas" },
  { id: 'move-naruto-with-iruka-10', level: 2, target: 10, hook: 'character.moved.by.source',
    predicate: { sourceName: 'IRUKA UMINO', targetName: 'NARUTO UZUMAKI' }, scope: 'cumulative',
    text_fr: "déplacer Naruto avec Iruka 10 fois",
    text_en: "move Naruto with Iruka 10 times",
    text_pt: "mova Naruto com Iruka 10 vezes",
    text_it: "sposta Naruto con Iruka 10 volte",
    text_pl: "przenieś Naruto za pomocą Iruki 10 razy",
    text_ja: "うみのイルカでうずまきナルトを10回移動させる",
    text_es: "mueve a Naruto con Iruka 10 veces" },
  { id: 'sacrifice-gemma-3', level: 2, target: 3, hook: 'character.sacrificed.with',
    predicate: { sourceName: 'GEMMA SHIRANUI' }, scope: 'cumulative',
    text_fr: "sacrifier Gemma pour une autre carte 3 fois",
    text_en: "sacrifice Gemma for another card 3 times",
    text_pt: "sacrifique Gemma por outra carta 3 vezes",
    text_it: "sacrifica Gemma per un'altra carta 3 volte",
    text_pl: "poświęć Gemmę dla innej karty 3 razy",
    text_ja: "不知火ゲンマを他のカードのために3回犠牲にする",
    text_es: "sacrifica a Gemma por otra carta 3 veces" },
  { id: 'hide-with-zabuza-5', level: 2, target: 5, hook: 'character.hidden.with.source',
    predicate: { sourceName: 'ZABUZA MOMOCHI' }, scope: 'cumulative',
    text_fr: "cacher 5 cartes avec Zabuza",
    text_en: "hide 5 cards with Zabuza",
    text_pt: "oculte 5 cartas com Zabuza",
    text_it: "nascondi 5 carte con Zabuza",
    text_pl: "ukryj 5 kart za pomocą Zabuzy",
    text_ja: "桃地再不斬でカードを5枚伏せる",
    text_es: "oculta 5 cartas con Zabuza" },
  { id: 'defeat-summon-with-manda-3', level: 2, target: 3, hook: 'character.defeated.with.source',
    predicate: { sourceName: 'MANDA', targetKeyword: 'Summon' }, scope: 'cumulative',
    text_fr: "vaincre 3 personnages Invocation avec Manda",
    text_en: "defeat 3 Summon characters with Manda",
    text_pt: "derrote 3 personagens de Invocação com Manda",
    text_it: "sconfiggi 3 personaggi Evocazione con Manda",
    text_pl: "pokonaj 3 postacie Przywołania za pomocą Mandy",
    text_ja: "マンダで口寄せキャラクターを3体撃破する",
    text_es: "derrota a 3 personajes de Invocación con Manda" },
  { id: 'hide-with-giant-spider-3', level: 2, target: 3, hook: 'character.hidden.with.source',
    predicate: { sourceName: 'KYODAIGUMO' }, scope: 'cumulative',
    text_fr: "cacher 3 personnages avec Araignée Géante",
    text_en: "hide 3 characters with Giant Spider",
    text_pt: "oculte 3 personagens com a Aranha Gigante",
    text_it: "nascondi 3 personaggi con il Ragno Gigante",
    text_pl: "ukryj 3 postacie za pomocą Gigantycznego Pająka",
    text_ja: "巨大蜘蛛でキャラクターを3体伏せる",
    text_es: "oculta a 3 personajes con la Araña Gigante" },
  { id: 'neji-remove-15-tokens-match', level: 2, target: 15, hook: 'tokens.removed.with.source',
    predicate: { sourceName: 'NEJI HYÛGA' }, scope: 'match',
    text_fr: "retirer 15 jetons de Puissance avec Neji en une partie",
    text_en: "remove 15 Power tokens with Neji in one match",
    text_pt: "remova 15 fichas de Poder com Neji em uma partida",
    text_it: "rimuovi 15 token Potenza con Neji in una partita",
    text_pl: "usuń 15 żetonów Siły za pomocą Nejiego w jednym meczu",
    text_ja: "1回の対戦で日向ネジでパワートークンを15個取り除く",
    text_es: "retira 15 fichas de Poder con Neji en una partida" },
  { id: 'sasuke-ambush-5', level: 2, target: 5, hook: 'ambush.activated.with.source',
    predicate: { sourceName: 'SASUKE UCHIWA' }, scope: 'cumulative',
    text_fr: "activer l'effet AMBUSH de Sasuke 5 fois",
    text_en: "trigger Sasuke's AMBUSH effect 5 times",
    text_pt: "ative o efeito AMBUSH de Sasuke 5 vezes",
    text_it: "attiva l'effetto AMBUSH di Sasuke 5 volte",
    text_pl: "aktywuj efekt AMBUSH Sasuke 5 razy",
    text_ja: "うちはサスケのAMBUSH効果を5回発動する",
    text_es: "activa el efecto AMBUSH de Sasuke 5 veces" },
  { id: 'kiba-hide-weakest-5', level: 2, target: 5, hook: 'character.hidden.weakest.with.source',
    predicate: { sourceName: 'KIBA INUZUKA' }, scope: 'cumulative',
    text_fr: "cacher 5 fois l'ennemi le moins puissant avec Kiba",
    text_en: "hide the weakest enemy with Kiba 5 times",
    text_pt: "oculte o inimigo mais fraco com Kiba 5 vezes",
    text_it: "nascondi il nemico più debole con Kiba 5 volte",
    text_pl: "ukryj najsłabszego wroga za pomocą Kiby 5 razy",
    text_ja: "犬塚キバで最も弱い敵を5回伏せる",
    text_es: "oculta al enemigo más débil con Kiba 5 veces" },
  { id: 'ebisu-draw-5', level: 2, target: 5, hook: 'card.drawn.via_effect.source',
    predicate: { sourceName: 'EBISU' }, scope: 'cumulative',
    text_fr: "piocher 5 fois grâce à Ebisu",
    text_en: "draw 5 times thanks to Ebisu",
    text_pt: "compre cartas 5 vezes graças a Ebisu",
    text_it: "pesca 5 volte grazie a Ebisu",
    text_pl: "dobierz karty 5 razy dzięki Ebisu",
    text_ja: "エビスで5回カードを引く",
    text_es: "roba 5 veces gracias a Ebisu" },
  { id: 'team7-same-mission', level: 2, target: 1, hook: 'mission.has.characters',
    predicate: { names: ['NARUTO UZUMAKI', 'SASUKE UCHIWA', 'SAKURA HARUNO'] }, scope: 'match',
    text_fr: "avoir Naruto, Sasuke et Sakura sur la même mission en une partie",
    text_en: "have Naruto, Sasuke and Sakura on the same mission in one match",
    text_pt: "tenha Naruto, Sasuke e Sakura na mesma missão em uma partida",
    text_it: "abbi Naruto, Sasuke e Sakura nella stessa missione in una partita",
    text_pl: "miej Naruto, Sasuke i Sakurę na tej samej misji w jednym meczu",
    text_ja: "1回の対戦でうずまきナルト、うちはサスケ、春野サクラを同じミッションに揃える",
    text_es: "ten a Naruto, Sasuke y Sakura en la misma misión en una partida" },
  { id: 'gamabunta-with-jiraya', level: 2, target: 1, hook: 'character.played.by.effect',
    predicate: { sourceName: 'JIRAYA', targetName: 'GAMA BUNTA' }, scope: 'match',
    text_fr: "invoquer Gama Bunta avec Jiraya en une partie",
    text_en: "summon Gama Bunta with Jiraya in one match",
    text_pt: "invoque Gamabunta com Jiraiya em uma partida",
    text_it: "evoca Gamabunta con Jiraiya in una partita",
    text_pl: "przywołaj Gamabuntę za pomocą Jiraiyi w jednym meczu",
    text_ja: "1回の対戦で自来也でガマ文太を口寄せする",
    text_es: "invoca a Gama Bunta con Jiraya en una partida" },
  { id: 'hiruzen-reduce-cost-leaf-5', level: 2, target: 5, hook: 'cost_reduction.with.source',
    predicate: { sourceName: 'HIRUZEN SARUTOBI', targetGroup: 'Leaf Village' }, scope: 'cumulative',
    text_fr: "réduire le coût d'un personnage du Village de la Feuille avec Hiruzen 5 fois",
    text_en: "reduce a Leaf Village character's cost with Hiruzen 5 times",
    text_pt: "reduza o custo de um personagem da Vila da Folha com Hiruzen 5 vezes",
    text_it: "riduci il costo di un personaggio del Villaggio della Foglia con Hiruzen 5 volte",
    text_pl: "obniż koszt postaci Wioski Liścia za pomocą Hiruzena 5 razy",
    text_ja: "猿飛ヒルゼンで木ノ葉隠れの里のキャラクターのコストを5回下げる",
    text_es: "reduce el coste de un personaje de la Aldea de la Hoja con Hiruzen 5 veces" },
  { id: 'tenten-defeat-hidden-match', level: 2, target: 1, hook: 'character.defeated.hidden.with.source',
    predicate: { sourceName: 'TENTEN' }, scope: 'match',
    text_fr: "vaincre une carte cachée avec Tenten en une partie",
    text_en: "defeat a hidden card with Tenten in one match",
    text_pt: "derrote uma carta oculta com Tenten em uma partida",
    text_it: "sconfiggi una carta nascosta con Tenten in una partita",
    text_pl: "pokonaj ukrytą kartę za pomocą Tenten w jednym meczu",
    text_ja: "1回の対戦でテンテンで伏せカードを撃破する",
    text_es: "derrota una carta oculta con Tenten en una partida" },
  { id: 'asuma-ambush-3', level: 2, target: 3, hook: 'ambush.activated.with.source',
    predicate: { sourceName: 'ASUMA SARUTOBI' }, scope: 'cumulative',
    text_fr: "activer l'AMBUSH d'Asuma 3 fois",
    text_en: "trigger Asuma's AMBUSH 3 times",
    text_pt: "ative o AMBUSH de Asuma 3 vezes",
    text_it: "attiva l'AMBUSH di Asuma 3 volte",
    text_pl: "aktywuj AMBUSH Asumy 3 razy",
    text_ja: "猿飛アスマのAMBUSHを3回発動する",
    text_es: "activa el AMBUSH de Asuma 3 veces" },
  { id: 'ai-medium-streak-3', level: 2, target: 1, hook: 'match.won.ai.streak',
    predicate: { difficulty: 'medium', streak: 3 }, scope: 'session',
    text_fr: "gagner 3 parties d'affilée contre l'IA Moyen",
    text_en: "win 3 matches in a row against the Medium AI",
    text_pt: "vença 3 partidas seguidas contra a IA Média",
    text_it: "vinci 3 partite di fila contro l'IA Media",
    text_pl: "wygraj 3 mecze z rzędu przeciwko SI na poziomie Średnim",
    text_ja: "AI（普通）に3連勝する",
    text_es: "gana 3 partidas seguidas contra la IA Media" },
  { id: 'evolving-wins-3', level: 2, target: 3, hook: 'match.won.evolving', scope: 'cumulative',
    text_fr: "gagner 3 parties en mode Evolving",
    text_en: "win 3 matches in Evolving Mode",
    text_pt: "vença 3 partidas no Evolving Mode",
    text_it: "vinci 3 partite in Evolving Mode",
    text_pl: "wygraj 3 mecze w trybie Evolving Mode",
    text_ja: "エボルビングモードで3回勝つ",
    text_es: "gana 3 partidas en el Modo Evolving" },
  { id: 'tokens-added-30', level: 2, target: 30, hook: 'power_token.added', scope: 'cumulative',
    text_fr: "ajouter 30 jetons de Puissance au total toutes parties confondues",
    text_en: "add 30 Power tokens across all matches",
    text_pt: "adicione 30 fichas de Poder em todas as partidas",
    text_it: "aggiungi 30 token Potenza in tutte le partite",
    text_pl: "dodaj 30 żetonów Siły we wszystkich meczach",
    text_ja: "全対戦でパワートークンを合計30個付与する",
    text_es: "añade 30 fichas de Poder en todas tus partidas" },
  { id: 'upgrade-stack-3', level: 2, target: 1, hook: 'upgrade.stack.depth',
    predicate: { depth: 3 }, scope: 'match',
    text_fr: "créer un stack d'upgrade de 3 cartes en une partie",
    text_en: "create an upgrade stack of 3 cards in one match",
    text_pt: "crie uma pilha de evolução de 3 cartas em uma partida",
    text_it: "crea una pila di evoluzione di 3 carte in una partita",
    text_pl: "utwórz stos ulepszeń z 3 kart w jednym meczu",
    text_ja: "1回の対戦で3枚のアップグレードの山を作る",
    text_es: "crea una pila de mejora de 3 cartas en una partida" },
  { id: 'social-add-friends-2', level: 2, target: 2, hook: 'social.friend.added', scope: 'cumulative',
    text_fr: "ajouter 2 amis",
    text_en: "add 2 friends",
    text_pt: "adicione 2 amigos",
    text_it: "aggiungi 2 amici",
    text_pl: "dodaj 2 znajomych",
    text_ja: "フレンドを2人追加する",
    text_es: "añade 2 amigos" },
  { id: 'daily-quests-5', level: 2, target: 5, hook: 'daily_quest.completed', scope: 'cumulative',
    text_fr: "compléter 5 quêtes quotidiennes (cumulatif)",
    text_en: "complete 5 daily quests (cumulative)",
    text_pt: "complete 5 missões diárias (cumulativo)",
    text_it: "completa 5 missioni giornaliere (cumulativo)",
    text_pl: "ukończ 5 codziennych zadań (łącznie)",
    text_ja: "デイリークエストを累計5つ達成する",
    text_es: "completa 5 misiones diarias (acumulado)" },
  { id: 'drawn-via-effect-20', level: 2, target: 20, hook: 'card.drawn.via_effect', scope: 'cumulative',
    text_fr: "piocher 20 cartes via effets toutes parties confondues",
    text_en: "draw 20 cards via effects across all matches",
    text_pt: "compre 20 cartas via efeitos em todas as partidas",
    text_it: "pesca 20 carte tramite effetti in tutte le partite",
    text_pl: "dobierz 20 kart za pomocą efektów we wszystkich meczach",
    text_ja: "全対戦で効果によりカードを合計20枚引く",
    text_es: "roba 20 cartas mediante efectos en todas tus partidas" },
  { id: 'matches-played-25', level: 2, target: 25, hook: 'match.played', scope: 'cumulative',
    text_fr: "jouer 25 parties tous modes confondus",
    text_en: "play 25 matches across all modes",
    text_pt: "jogue 25 partidas em todos os modos",
    text_it: "gioca 25 partite in tutte le modalità",
    text_pl: "rozegraj 25 meczów we wszystkich trybach",
    text_ja: "全モードで合計25回対戦する",
    text_es: "juega 25 partidas en todos los modos" },
  { id: 'mission-A-won-1', level: 2, target: 1, hook: 'mission.won',
    predicate: { rank: 'A' }, scope: 'cumulative',
    text_fr: "gagner 1 mission de rang A",
    text_en: "win 1 rank A mission",
    text_pt: "vença 1 missão de rank A",
    text_it: "vinci 1 missione di rank A",
    text_pl: "wygraj 1 misję rangi A",
    text_ja: "ランクAのミッションを1つ勝ち取る",
    text_es: "gana 1 misión de rango A" },
  { id: 'tournament-single-won-1', level: 2, target: 1, hook: 'tournament.won.single', scope: 'cumulative',
    text_fr: "gagner 1 tournoi Single Elimination",
    text_en: "win 1 Single Elimination tournament",
    text_pt: "vença 1 torneio de Eliminação Simples",
    text_it: "vinci 1 torneo a Eliminazione Diretta",
    text_pl: "wygraj 1 turniej Pojedynczej Eliminacji",
    text_ja: "シングルエリミネーションのトーナメントで1回優勝する",
    text_es: "gana 1 torneo de Eliminación Directa" },

  { id: 'discard-50', level: 3, target: 50, hook: 'card.discarded', scope: 'cumulative',
    text_fr: "défausser 50 cartes",
    text_en: "discard 50 cards",
    text_pt: "descarte 50 cartas",
    text_it: "scarta 50 carte",
    text_pl: "odrzuć 50 kart",
    text_ja: "カードを50枚捨てる",
    text_es: "descarta 50 cartas" },
  { id: 'neji-remove-10-tokens-match', level: 3, target: 10, hook: 'tokens.removed.with.source',
    predicate: { sourceName: 'NEJI HYÛGA' }, scope: 'match',
    text_fr: "retirer 10 jetons de Puissance avec Neji en une partie",
    text_en: "remove 10 Power tokens with Neji in one match",
    text_pt: "remova 10 fichas de Poder com Neji em uma partida",
    text_it: "rimuovi 10 token Potenza con Neji in una partita",
    text_pl: "usuń 10 żetonów Siły za pomocą Nejiego w jednym meczu",
    text_ja: "1回の対戦で日向ネジでパワートークンを10個取り除く",
    text_es: "retira 10 fichas de Poder con Neji en una partida" },
  { id: 'rock-lee-10-tokens-match', level: 3, target: 1, hook: 'character.power_tokens.threshold',
    predicate: { name: 'ROCK LEE', threshold: 10 }, scope: 'match',
    text_fr: "avoir un Rock Lee avec 10 jetons de Puissance ou plus en une partie",
    text_en: "have a Rock Lee with 10 or more Power tokens in one match",
    text_pt: "tenha um Rock Lee com 10 ou mais fichas de Poder em uma partida",
    text_it: "abbi un Rock Lee con 10 o più token Potenza in una partita",
    text_pl: "miej Rocka Lee z 10 lub więcej żetonami Siły w jednym meczu",
    text_ja: "1回の対戦でロック・リーにパワートークンを10個以上持たせる",
    text_es: "ten un Rock Lee con 10 o más fichas de Poder en una partida" },
  { id: 'maito-gai-10-tokens-match', level: 3, target: 1, hook: 'character.power_tokens.threshold',
    predicate: { name: 'GAÏ MAITO', threshold: 10 }, scope: 'match',
    text_fr: "avoir un Maître Gai avec 10 jetons de Puissance ou plus en une partie",
    text_en: "have a Might Guy with 10 or more Power tokens in one match",
    text_pt: "tenha um Might Guy com 10 ou mais fichas de Poder em uma partida",
    text_it: "abbi un Might Guy con 10 o più token Potenza in una partita",
    text_pl: "miej Might Guya z 10 lub więcej żetonami Siły w jednym meczu",
    text_ja: "1回の対戦でマイト・ガイにパワートークンを10個以上持たせる",
    text_es: "ten un Might Guy con 10 o más fichas de Poder en una partida" },
  { id: 'draw-10-via-effects-match', level: 3, target: 10, hook: 'card.drawn.via_effect', scope: 'match',
    text_fr: "piocher 10 cartes ou plus en une partie grâce à des effets",
    text_en: "draw 10 or more cards in one match via effects",
    text_pt: "compre 10 ou mais cartas em uma partida via efeitos",
    text_it: "pesca 10 o più carte in una partita tramite effetti",
    text_pl: "dobierz 10 lub więcej kart w jednym meczu za pomocą efektów",
    text_ja: "1回の対戦で効果によりカードを10枚以上引く",
    text_es: "roba 10 o más cartas en una partida mediante efectos" },
  { id: 'sakon-copy-5', level: 3, target: 5, hook: 'effect.copied.with.source',
    predicate: { sourceName: 'SAKON' }, scope: 'cumulative',
    text_fr: "copier 5 effets avec Sakon",
    text_en: "copy 5 effects with Sakon",
    text_pt: "copie 5 efeitos com Sakon",
    text_it: "copia 5 effetti con Sakon",
    text_pl: "skopiuj 5 efektów za pomocą Sakona",
    text_ja: "左近で効果を5回コピーする",
    text_es: "copia 5 efectos con Sakon" },
  { id: 'ino-control-5', level: 3, target: 5, hook: 'character.controlled.with.source',
    predicate: { sourceName: 'INO YAMANAKA' }, scope: 'cumulative',
    text_fr: "prendre le contrôle de 5 personnages avec Ino",
    text_en: "take control of 5 characters with Ino",
    text_pt: "assuma o controle de 5 personagens com Ino",
    text_it: "prendi il controllo di 5 personaggi con Ino",
    text_pl: "przejmij kontrolę nad 5 postaciami za pomocą Ino",
    text_ja: "山中いのでキャラクターを5体コントロールする",
    text_es: "toma el control de 5 personajes con Ino" },
  { id: 'itachi-10-power-match', level: 3, target: 1, hook: 'character.power.threshold',
    predicate: { name: 'ITACHI UCHIWA', threshold: 10 }, scope: 'match',
    text_fr: "avoir un Itachi avec 10 Puissance ou plus en une partie",
    text_en: "have an Itachi with 10 or more Power in one match",
    text_pt: "tenha um Itachi com 10 ou mais de Poder em uma partida",
    text_it: "abbi un Itachi con 10 o più Potenza in una partita",
    text_pl: "miej Itachiego z 10 lub więcej Siły w jednym meczu",
    text_ja: "1回の対戦でうちはイタチをパワー10以上にする",
    text_es: "ten un Itachi con 10 o más de Poder en una partida" },
  { id: 'temari-move-friendly-10', level: 3, target: 10, hook: 'character.moved.with.source',
    predicate: { sourceName: 'TEMARI', friendly: true }, scope: 'cumulative',
    text_fr: "déplacer 10 alliés avec Temari toutes parties confondues",
    text_en: "move 10 allies with Temari across all matches",
    text_pt: "mova 10 aliados com Temari em todas as partidas",
    text_it: "sposta 10 alleati con Temari in tutte le partite",
    text_pl: "przenieś 10 sojuszników za pomocą Temari we wszystkich meczach",
    text_ja: "全対戦でテマリで味方を合計10体移動させる",
    text_es: "mueve 10 aliados con Temari en todas tus partidas" },
  { id: 'kidomaru-defeat-5', level: 3, target: 5, hook: 'character.defeated.with.source',
    predicate: { sourceName: 'KIDÔMARU' }, scope: 'cumulative',
    text_fr: "vaincre 5 personnages avec Kidômaru toutes parties confondues",
    text_en: "defeat 5 characters with Kidômaru across all matches",
    text_pt: "derrote 5 personagens com Kidômaru em todas as partidas",
    text_it: "sconfiggi 5 personaggi con Kidômaru in tutte le partite",
    text_pl: "pokonaj 5 postaci za pomocą Kidômaru we wszystkich meczach",
    text_ja: "全対戦で鬼童丸でキャラクターを合計5体撃破する",
    text_es: "derrota a 5 personajes con Kidômaru en todas tus partidas" },
  { id: 'kakashi-ambush-copy-5', level: 3, target: 5, hook: 'effect.copied.via_ambush.with.source',
    predicate: { sourceName: 'KAKASHI HATAKE' }, scope: 'cumulative',
    text_fr: "utiliser l'AMBUSH de Kakashi pour copier 5 effets",
    text_en: "use Kakashi's AMBUSH to copy 5 effects",
    text_pt: "use o AMBUSH de Kakashi para copiar 5 efeitos",
    text_it: "usa l'AMBUSH di Kakashi per copiare 5 effetti",
    text_pl: "użyj AMBUSH Kakashiego, aby skopiować 5 efektów",
    text_ja: "はたけカカシのAMBUSHで効果を5回コピーする",
    text_es: "usa el AMBUSH de Kakashi para copiar 5 efectos" },
  { id: 'defeat-kyubi', level: 3, target: 1, hook: 'character.defeated.by.name',
    predicate: { name: 'KYÛBI' }, scope: 'cumulative',
    text_fr: "vaincre un Kyûbi en jeu",
    text_en: "defeat a Kyûbi in play",
    text_pt: "derrote uma Kyûbi em jogo",
    text_it: "sconfiggi un Kyûbi in gioco",
    text_pl: "pokonaj Kyûbiego w grze",
    text_ja: "場の九尾を撃破する",
    text_es: "derrota a un Kyûbi en juego" },
  { id: 'kabuto-hide-5', level: 3, target: 5, hook: 'character.hidden.with.source',
    predicate: { sourceName: 'KABUTO YAKUSHI' }, scope: 'cumulative',
    text_fr: "cacher 5 personnages avec Kabuto toutes parties confondues",
    text_en: "hide 5 characters with Kabuto across all matches",
    text_pt: "oculte 5 personagens com Kabuto em todas as partidas",
    text_it: "nascondi 5 personaggi con Kabuto in tutte le partite",
    text_pl: "ukryj 5 postaci za pomocą Kabuto we wszystkich meczach",
    text_ja: "全対戦で薬師カブトでキャラクターを合計5体伏せる",
    text_es: "oculta a 5 personajes con Kabuto en todas tus partidas" },
  { id: 'reveal-for-ambush-10', level: 3, target: 10, hook: 'ambush.activated.via_reveal',
    scope: 'cumulative',
    text_fr: "révéler une carte cachée pour activer son AMBUSH 10 fois",
    text_en: "reveal a hidden card to trigger its AMBUSH 10 times",
    text_pt: "revele uma carta oculta para ativar seu AMBUSH 10 vezes",
    text_it: "rivela una carta nascosta per attivare il suo AMBUSH 10 volte",
    text_pl: "odkryj ukrytą kartę, aby aktywować jej AMBUSH 10 razy",
    text_ja: "伏せカードを表にしてAMBUSHを10回発動する",
    text_es: "revela una carta oculta para activar su AMBUSH 10 veces" },
  { id: 'ranked-streak-5', level: 3, target: 1, hook: 'ranked.win.streak',
    predicate: { streak: 5 }, scope: 'session',
    text_fr: "gagner 5 parties d'affilée en classé",
    text_en: "win 5 ranked matches in a row",
    text_pt: "vença 5 partidas ranqueadas seguidas",
    text_it: "vinci 5 partite classificate di fila",
    text_pl: "wygraj 5 meczów rankingowych z rzędu",
    text_ja: "ランク戦で5連勝する",
    text_es: "gana 5 partidas clasificatorias seguidas" },
  { id: 'evolving-wins-10', level: 3, target: 10, hook: 'match.won.evolving', scope: 'cumulative',
    text_fr: "gagner 10 parties en mode Evolving",
    text_en: "win 10 matches in Evolving Mode",
    text_pt: "vença 10 partidas no Evolving Mode",
    text_it: "vinci 10 partite in Evolving Mode",
    text_pl: "wygraj 10 meczów w trybie Evolving Mode",
    text_ja: "エボルビングモードで10回勝つ",
    text_es: "gana 10 partidas en el Modo Evolving" },
  { id: 'ai-expert-streak-5', level: 3, target: 1, hook: 'match.won.ai.streak',
    predicate: { difficulty: 'expert', streak: 5 }, scope: 'session',
    text_fr: "gagner 5 parties d'affilée contre l'IA Expert",
    text_en: "win 5 matches in a row against the Expert AI",
    text_pt: "vença 5 partidas seguidas contra a IA Expert",
    text_it: "vinci 5 partite di fila contro l'IA Expert",
    text_pl: "wygraj 5 meczów z rzędu przeciwko SI na poziomie Expert",
    text_ja: "AI（達人）に5連勝する",
    text_es: "gana 5 partidas seguidas contra la IA Experta" },
  { id: 'elo-reach-chunin', level: 3, target: 1, hook: 'elo.tier.reached',
    predicate: { tier: 'chunin' }, scope: 'cumulative',
    text_fr: "atteindre le rang Chûnin en ELO classique",
    text_en: "reach the Chûnin rank in classic ELO",
    text_pt: "alcance a patente Chûnin no ELO clássico",
    text_it: "raggiungi il grado Chûnin nell'ELO classico",
    text_pl: "osiągnij rangę Chûnin w klasycznym ELO",
    text_ja: "通常ELOで中忍ランクに到達する",
    text_es: "alcanza el rango Chûnin en el ELO clásico" },
  { id: 'tournament-swiss-won-1', level: 3, target: 1, hook: 'tournament.won.swiss', scope: 'cumulative',
    text_fr: "gagner 1 tournoi Swiss",
    text_en: "win 1 Swiss tournament",
    text_pt: "vença 1 torneio suíço",
    text_it: "vinci 1 torneo svizzero",
    text_pl: "wygraj 1 turniej szwajcarski",
    text_ja: "スイスドロー式トーナメントで1回優勝する",
    text_es: "gana 1 torneo suizo" },
  { id: 'tokens-added-50-session', level: 3, target: 50, hook: 'power_token.added', scope: 'session',
    text_fr: "ajouter 50 jetons de Puissance en une session de jeu",
    text_en: "add 50 Power tokens in one play session",
    text_pt: "adicione 50 fichas de Poder em uma sessão de jogo",
    text_it: "aggiungi 50 token Potenza in una sessione di gioco",
    text_pl: "dodaj 50 żetonów Siły w jednej sesji gry",
    text_ja: "1回のプレイセッションでパワートークンを50個付与する",
    text_es: "añade 50 fichas de Poder en una sesión de juego" },
  { id: 'hide-25-session', level: 3, target: 25, hook: 'character.hidden', scope: 'session',
    text_fr: "cacher 25 personnages en une session de jeu",
    text_en: "hide 25 characters in one play session",
    text_pt: "oculte 25 personagens em uma sessão de jogo",
    text_it: "nascondi 25 personaggi in una sessione di gioco",
    text_pl: "ukryj 25 postaci w jednej sesji gry",
    text_ja: "1回のプレイセッションでキャラクターを25体伏せる",
    text_es: "oculta a 25 personajes en una sesión de juego" },
  { id: 'daily-quests-15', level: 3, target: 15, hook: 'daily_quest.completed', scope: 'cumulative',
    text_fr: "compléter 15 quêtes quotidiennes (cumulatif)",
    text_en: "complete 15 daily quests (cumulative)",
    text_pt: "complete 15 missões diárias (cumulativo)",
    text_it: "completa 15 missioni giornaliere (cumulativo)",
    text_pl: "ukończ 15 codziennych zadań (łącznie)",
    text_ja: "デイリークエストを累計15達成する",
    text_es: "completa 15 misiones diarias (acumulado)" },
  { id: 'mission-points-12-match', level: 3, target: 1, hook: 'mission_points.scored.match', predicate: { threshold: 12 }, scope: 'match',
    text_fr: "atteindre 12 points de mission en une seule partie",
    text_en: "reach 12 mission points in a single match",
    text_pt: "alcance 12 pontos de missão em uma única partida",
    text_it: "raggiungi 12 punti missione in una singola partita",
    text_pl: "osiągnij 12 punktów misji w jednym meczu",
    text_ja: "1回の対戦でミッションポイントを12点獲得する",
    text_es: "alcanza 12 puntos de misión en una sola partida" },
  { id: 'ranked-mono-sound-wins-10', level: 3, target: 10, hook: 'ranked.win.deck',
    predicate: { monoGroup: 'Sound Village' }, scope: 'cumulative',
    text_fr: "gagner 10 parties en classé avec un deck contenant uniquement des cartes du Village du Son",
    text_en: "win 10 ranked matches with a deck made only of Sound Village cards",
    text_pt: "vença 10 partidas ranqueadas com um deck feito só de cartas da Vila do Som",
    text_it: "vinci 10 partite classificate con un mazzo composto solo da carte del Villaggio del Suono",
    text_pl: "wygraj 10 meczów rankingowych talią złożoną wyłącznie z kart Wioski Dźwięku",
    text_ja: "音隠れの里のカードだけのデッキでランク戦に10回勝つ",
    text_es: "gana 10 partidas clasificatorias con un mazo formado solo por cartas de la Aldea del Sonido" },
  { id: 'win-without-defeats-own', level: 3, target: 1, hook: 'match.won.no_defeats_own', scope: 'cumulative',
    text_fr: "gagner une partie sans qu'aucun de tes personnages soit vaincu",
    text_en: "win a match without losing any of your characters",
    text_pt: "vença uma partida sem perder nenhum dos seus personagens",
    text_it: "vinci una partita senza perdere nessuno dei tuoi personaggi",
    text_pl: "wygraj mecz, nie tracąc żadnej ze swoich postaci",
    text_ja: "自分のキャラクターを1体も失わずに対戦に勝つ",
    text_es: "gana una partida sin perder ninguno de tus personajes" },

  { id: 'kisame-remove-30', level: 4, target: 30, hook: 'tokens.removed.with.source',
    predicate: { sourceName: 'KISAME HOSHIGAKI' }, scope: 'cumulative',
    text_fr: "retirer 30 jetons de Puissance avec une carte Kisame",
    text_en: "remove 30 Power tokens with a Kisame card",
    text_pt: "remova 30 fichas de Poder com uma carta Kisame",
    text_it: "rimuovi 30 token Potenza con una carta Kisame",
    text_pl: "usuń 30 żetonów Siły za pomocą karty Kisame",
    text_ja: "干柿鬼鮫のカードでパワートークンを30個取り除く",
    text_es: "retira 30 fichas de Poder con una carta de Kisame" },
  { id: 'ranked-wins-with-ino-shika-cho-20', level: 4, target: 20, hook: 'ranked.win.deck.contains',
    predicate: { names: ['INO YAMANAKA', 'SHIKAMARU NARA', 'CHÔJI AKIMICHI'] }, scope: 'cumulative',
    text_fr: "gagner 20 parties en classé avec un deck contenant une carte Ino, une carte Shikamaru et une carte Chôji",
    text_en: "win 20 ranked matches with a deck containing an Ino card, a Shikamaru card and a Chôji card",
    text_pt: "vença 20 partidas ranqueadas com um deck contendo uma carta Ino, uma carta Shikamaru e uma carta Chôji",
    text_it: "vinci 20 partite classificate con un mazzo che contiene una carta Ino, una carta Shikamaru e una carta Chôji",
    text_pl: "wygraj 20 meczów rankingowych talią zawierającą kartę Ino, kartę Shikamaru i kartę Chôji",
    text_ja: "山中いの、奈良シカマル、秋道チョウジのカードを含むデッキでランク戦に20回勝つ",
    text_es: "gana 20 partidas clasificatorias con un mazo que contenga una carta de Ino, una de Shikamaru y una de Chôji" },
  { id: 'discard-100', level: 4, target: 100, hook: 'card.discarded', scope: 'cumulative',
    text_fr: "défausser 100 cartes",
    text_en: "discard 100 cards",
    text_pt: "descarte 100 cartas",
    text_it: "scarta 100 carte",
    text_pl: "odrzuć 100 kart",
    text_ja: "カードを100枚捨てる",
    text_es: "descarta 100 cartas" },
  { id: 'neji-defeat-power4-power6-same-action', level: 4, target: 1, hook: 'character.defeated.with.source.power.combo',
    predicate: { sourceName: 'NEJI HYÛGA', powers: [4, 6] }, scope: 'match',
    text_fr: "vaincre une carte de Puissance 4 et une carte de Puissance 6 avec Neji avec la même action",
    text_en: "defeat a 4 Power card and a 6 Power card with Neji in the same action",
    text_pt: "derrote uma carta de 4 de Poder e uma de 6 de Poder com Neji na mesma ação",
    text_it: "sconfiggi una carta da 4 Potenza e una da 6 Potenza con Neji nella stessa azione",
    text_pl: "pokonaj kartę o Sile 4 i kartę o Sile 6 za pomocą Nejiego w tej samej akcji",
    text_ja: "日向ネジで同じアクションでパワー4とパワー6のカードを撃破する",
    text_es: "derrota una carta de 4 de Poder y una de 6 de Poder con Neji en la misma acción" },
  { id: 'kakashi-copy-20', level: 4, target: 20, hook: 'effect.copied.with.source',
    predicate: { sourceName: 'KAKASHI HATAKE' }, scope: 'cumulative',
    text_fr: "copier 20 effets adverses avec un Kakashi",
    text_en: "copy 20 enemy effects with a Kakashi",
    text_pt: "copie 20 efeitos inimigos com um Kakashi",
    text_it: "copia 20 effetti nemici con un Kakashi",
    text_pl: "skopiuj 20 wrogich efektów za pomocą Kakashiego",
    text_ja: "はたけカカシで敵の効果を20回コピーする",
    text_es: "copia 20 efectos enemigos con un Kakashi" },
  { id: 'ranked-win-no-effects-3', level: 4, target: 3, hook: 'ranked.win.no_effects_used', scope: 'cumulative',
    text_fr: "gagner 3 parties en classé sans utiliser d'effet",
    text_en: "win 3 ranked matches without using any effect",
    text_pt: "vença 3 partidas ranqueadas sem usar nenhum efeito",
    text_it: "vinci 3 partite classificate senza usare alcun effetto",
    text_pl: "wygraj 3 mecze rankingowe bez użycia żadnego efektu",
    text_ja: "効果を一切使わずにランク戦に3回勝つ",
    text_es: "gana 3 partidas clasificatorias sin usar ningún efecto" },
  { id: 'ranked-wins-50', level: 4, target: 50, hook: 'ranked.win', scope: 'cumulative',
    text_fr: "gagner 50 parties en classé",
    text_en: "win 50 ranked matches",
    text_pt: "vença 50 partidas ranqueadas",
    text_it: "vinci 50 partite classificate",
    text_pl: "wygraj 50 meczów rankingowych",
    text_ja: "ランク戦に50回勝つ",
    text_es: "gana 50 partidas clasificatorias" },
  { id: 'elo-reach-hokage', level: 4, target: 1, hook: 'elo.tier.reached',
    predicate: { tier: 'will_of_fire' }, scope: 'cumulative',
    text_fr: "atteindre le rang Héritier de la Volonté du Feu en ELO classique",
    text_en: "reach the Will of Fire rank in classic ELO",
    text_pt: "alcance a patente Vontade do Fogo no ELO clássico",
    text_it: "raggiungi il grado Volontà del Fuoco nell'ELO classico",
    text_pl: "osiągnij rangę Woli Ognia w klasycznym ELO",
    text_ja: "通常ELOで「火の意志を継ぐ者」ランクに到達する",
    text_es: "alcanza el rango Voluntad de Fuego en el ELO clásico" },
  { id: 'ranked-streak-10', level: 4, target: 1, hook: 'ranked.win.streak',
    predicate: { streak: 10 }, scope: 'session',
    text_fr: "gagner 10 parties d'affilée en classé",
    text_en: "win 10 ranked matches in a row",
    text_pt: "vença 10 partidas ranqueadas seguidas",
    text_it: "vinci 10 partite classificate di fila",
    text_pl: "wygraj 10 meczów rankingowych z rzędu",
    text_ja: "ランク戦で10連勝する",
    text_es: "gana 10 partidas clasificatorias seguidas" },
  { id: 'evolving-wins-30', level: 4, target: 30, hook: 'match.won.evolving', scope: 'cumulative',
    text_fr: "gagner 30 parties en mode Evolving",
    text_en: "win 30 matches in Evolving Mode",
    text_pt: "vença 30 partidas no Evolving Mode",
    text_it: "vinci 30 partite in Evolving Mode",
    text_pl: "wygraj 30 meczów w trybie Evolving Mode",
    text_ja: "エボルビングモードで30回勝つ",
    text_es: "gana 30 partidas en el Modo Evolving" },
  { id: 'tournament-swiss-won-5', level: 4, target: 5, hook: 'tournament.won.swiss', scope: 'cumulative',
    text_fr: "gagner 5 tournois Swiss",
    text_en: "win 5 Swiss tournaments",
    text_pt: "vença 5 torneios suíços",
    text_it: "vinci 5 tornei svizzeri",
    text_pl: "wygraj 5 turniejów szwajcarskich",
    text_ja: "スイスドロー式トーナメントで5回優勝する",
    text_es: "gana 5 torneos suizos" },
  { id: 'tournament-single-won-5', level: 4, target: 5, hook: 'tournament.won.single', scope: 'cumulative',
    text_fr: "gagner 5 tournois Single Elimination",
    text_en: "win 5 Single Elimination tournaments",
    text_pt: "vença 5 torneios de Eliminação Simples",
    text_it: "vinci 5 tornei a Eliminazione Diretta",
    text_pl: "wygraj 5 turniejów Pojedynczej Eliminacji",
    text_ja: "シングルエリミネーションのトーナメントで5回優勝する",
    text_es: "gana 5 torneos de Eliminación Directa" },
  { id: 'defeat-100-cumulative', level: 4, target: 100, hook: 'character.defeated', scope: 'cumulative',
    text_fr: "vaincre 100 personnages au total",
    text_en: "defeat 100 characters in total",
    text_pt: "derrote 100 personagens no total",
    text_it: "sconfiggi 100 personaggi in totale",
    text_pl: "pokonaj 100 postaci łącznie",
    text_ja: "キャラクターを合計100体撃破する",
    text_es: "derrota a 100 personajes en total" },
  { id: 'hide-100-cumulative', level: 4, target: 100, hook: 'character.hidden', scope: 'cumulative',
    text_fr: "cacher 100 personnages au total",
    text_en: "hide 100 characters in total",
    text_pt: "oculte 100 personagens no total",
    text_it: "nascondi 100 personaggi in totale",
    text_pl: "ukryj 100 postaci łącznie",
    text_ja: "キャラクターを合計100体伏せる",
    text_es: "oculta a 100 personajes en total" },
  { id: 'tokens-added-100', level: 4, target: 100, hook: 'power_token.added', scope: 'cumulative',
    text_fr: "ajouter 100 jetons de Puissance au total",
    text_en: "add 100 Power tokens in total",
    text_pt: "adicione 100 fichas de Poder no total",
    text_it: "aggiungi 100 token Potenza in totale",
    text_pl: "dodaj 100 żetonów Siły łącznie",
    text_ja: "パワートークンを合計100個付与する",
    text_es: "añade 100 fichas de Poder en total" },
  { id: 'sealed-wins-10', level: 4, target: 10, hook: 'match.won.sealed', scope: 'cumulative',
    text_fr: "gagner 10 parties en scellé",
    text_en: "win 10 sealed matches",
    text_pt: "vença 10 partidas sealed",
    text_it: "vinci 10 partite sealed",
    text_pl: "wygraj 10 meczów sealed",
    text_ja: "シールド戦に10回勝つ",
    text_es: "gana 10 partidas selladas" },
  { id: 'short-wins-5', level: 4, target: 5, hook: 'match.won.short',
    predicate: { maxRound: 3 }, scope: 'cumulative',
    text_fr: "gagner 5 parties en moins de 4 tours",
    text_en: "win 5 matches in fewer than 4 rounds",
    text_pt: "vença 5 partidas em menos de 4 rodadas",
    text_it: "vinci 5 partite in meno di 4 turni",
    text_pl: "wygraj 5 meczów w mniej niż 4 rundy",
    text_ja: "4ラウンド未満で5回勝つ",
    text_es: "gana 5 partidas en menos de 4 rondas" },
  { id: 'daily-quests-30', level: 4, target: 30, hook: 'daily_quest.completed', scope: 'cumulative',
    text_fr: "compléter 30 quêtes quotidiennes (cumulatif)",
    text_en: "complete 30 daily quests (cumulative)",
    text_pt: "complete 30 missões diárias (cumulativo)",
    text_it: "completa 30 missioni giornaliere (cumulativo)",
    text_pl: "ukończ 30 codziennych zadań (łącznie)",
    text_ja: "デイリークエストを累計30達成する",
    text_es: "completa 30 misiones diarias (acumulado)" },
  { id: 'boosters-opened-25', level: 4, target: 25, hook: 'booster.opened', scope: 'cumulative',
    text_fr: "ouvrir 25 boosters variantes",
    text_en: "open 25 variant boosters",
    text_pt: "abra 25 boosters de variantes",
    text_it: "apri 25 booster di varianti",
    text_pl: "otwórz 25 boosterów wariantów",
    text_ja: "バリアントブースターを25個開ける",
    text_es: "abre 25 sobres de variantes" },
  { id: 'tournament-mono-village-won', level: 4, target: 1, hook: 'tournament.won.mono_village', scope: 'cumulative',
    text_fr: "gagner un tournoi avec un deck mono-village",
    text_en: "win a tournament with a mono-village deck",
    text_pt: "vença um torneio com um deck de vila única",
    text_it: "vinci un torneo con un mazzo mono-villaggio",
    text_pl: "wygraj turniej talią jednej wioski",
    text_ja: "単一の里だけのデッキでトーナメントに優勝する",
    text_es: "gana un torneo con un mazo de una sola aldea" },
  { id: 'win-deck-power-minimum-4', level: 4, target: 1, hook: 'match.won.deck.power_minimum',
    predicate: { minPrinted: 4 }, scope: 'cumulative',
    text_fr: "gagner avec un deck contenant uniquement des personnages avec 4 ou plus de Puissance imprimée",
    text_en: "win with a deck made only of characters with 4 or more printed Power",
    text_pt: "vença com um deck feito só de personagens com Poder impresso 4 ou mais",
    text_it: "vinci con un mazzo composto solo da personaggi con Potenza stampata 4 o più",
    text_pl: "wygraj talią złożoną wyłącznie z postaci o nadrukowanej Sile 4 lub więcej",
    text_ja: "印刷パワー4以上のキャラクターだけのデッキで勝つ",
    text_es: "gana con un mazo formado solo por personajes con 4 o más de Poder impreso" },
  { id: 'discard-200', level: 4, target: 200, hook: 'card.discarded', scope: 'cumulative',
    text_fr: "défausser 200 cartes au total",
    text_en: "discard 200 cards in total",
    text_pt: "descarte 200 cartas no total",
    text_it: "scarta 200 carte in totale",
    text_pl: "odrzuć 200 kart łącznie",
    text_ja: "カードを合計200枚捨てる",
    text_es: "descarta 200 cartas en total" },
  { id: 'battlepass-tier-50', level: 4, target: 1, hook: 'battlepass.tier.reached',
    predicate: { tier: 50 }, scope: 'cumulative',
    text_fr: "atteindre la Récompense de niveau 50",
    text_en: "reach Tier Reward 50",
    text_pt: "alcance a Recompensa de Nível 50",
    text_it: "raggiungi la Ricompensa di Livello 50",
    text_pl: "osiągnij Nagrodę Poziomu 50",
    text_ja: "報酬ティア50に到達する",
    text_es: "alcanza el Nivel de Recompensa 50" },
  { id: 'reveal-25-cumulative', level: 4, target: 25, hook: 'character.revealed', scope: 'cumulative',
    text_fr: "révéler 25 personnages cachés au total",
    text_en: "reveal 25 hidden characters in total",
    text_pt: "revele 25 personagens ocultos no total",
    text_it: "rivela 25 personaggi nascosti in totale",
    text_pl: "odkryj 25 ukrytych postaci łącznie",
    text_ja: "伏せキャラクターを合計25体表にする",
    text_es: "revela a 25 personajes ocultos en total" },
  { id: 'defeat-50-cumulative', level: 4, target: 50, hook: 'character.defeated', scope: 'cumulative',
    text_fr: "vaincre 50 personnages au total",
    text_en: "defeat 50 characters in total",
    text_pt: "derrote 50 personagens no total",
    text_it: "sconfiggi 50 personaggi in totale",
    text_pl: "pokonaj 50 postaci łącznie",
    text_ja: "キャラクターを合計50体撃破する",
    text_es: "derrota a 50 personajes en total" },

  { id: 'card-play-naruto-1', level: 1, target: 1, hook: 'character.played', predicate: { targetName: 'NARUTO UZUMAKI' }, scope: 'cumulative',
    text_fr: "jouer 1 carte Naruto Uzumaki",
    text_en: "play 1 Naruto Uzumaki card",
    text_pt: "jogue 1 carta Naruto Uzumaki",
    text_it: "gioca 1 carta Naruto Uzumaki",
    text_pl: "zagraj 1 kartę Naruto Uzumaki",
    text_ja: "うずまきナルトのカードを1枚出す",
    text_es: "juega 1 carta de Naruto Uzumaki" },
  { id: 'card-play-sasuke-1', level: 1, target: 1, hook: 'character.played', predicate: { targetName: 'SASUKE UCHIWA' }, scope: 'cumulative',
    text_fr: "jouer 1 carte Sasuke Uchiwa",
    text_en: "play 1 Sasuke Uchiwa card",
    text_pt: "jogue 1 carta Sasuke Uchiha",
    text_it: "gioca 1 carta Sasuke Uchiha",
    text_pl: "zagraj 1 kartę Sasuke Uchiha",
    text_ja: "うちはサスケのカードを1枚出す",
    text_es: "juega 1 carta de Sasuke Uchiwa" },
  { id: 'card-play-sakura-1', level: 1, target: 1, hook: 'character.played', predicate: { targetName: 'SAKURA HARUNO' }, scope: 'cumulative',
    text_fr: "jouer 1 carte Sakura Haruno",
    text_en: "play 1 Sakura Haruno card",
    text_pt: "jogue 1 carta Sakura Haruno",
    text_it: "gioca 1 carta Sakura Haruno",
    text_pl: "zagraj 1 kartę Sakura Haruno",
    text_ja: "春野サクラのカードを1枚出す",
    text_es: "juega 1 carta de Sakura Haruno" },
  { id: 'card-play-kakashi-1', level: 1, target: 1, hook: 'character.played', predicate: { targetName: 'KAKASHI HATAKE' }, scope: 'cumulative',
    text_fr: "jouer 1 carte Kakashi Hatake",
    text_en: "play 1 Kakashi Hatake card",
    text_pt: "jogue 1 carta Kakashi Hatake",
    text_it: "gioca 1 carta Kakashi Hatake",
    text_pl: "zagraj 1 kartę Kakashi Hatake",
    text_ja: "はたけカカシのカードを1枚出す",
    text_es: "juega 1 carta de Kakashi Hatake" },
  { id: 'card-play-itachi-1', level: 1, target: 1, hook: 'character.played', predicate: { targetName: 'ITACHI UCHIWA' }, scope: 'cumulative',
    text_fr: "jouer 1 carte Itachi Uchiwa",
    text_en: "play 1 Itachi Uchiwa card",
    text_pt: "jogue 1 carta Itachi Uchiha",
    text_it: "gioca 1 carta Itachi Uchiha",
    text_pl: "zagraj 1 kartę Itachi Uchiha",
    text_ja: "うちはイタチのカードを1枚出す",
    text_es: "juega 1 carta de Itachi Uchiwa" },
  { id: 'card-play-gaara-1', level: 1, target: 1, hook: 'character.played', predicate: { targetName: 'GAARA' }, scope: 'cumulative',
    text_fr: "jouer 1 carte Gaara",
    text_en: "play 1 Gaara card",
    text_pt: "jogue 1 carta Gaara",
    text_it: "gioca 1 carta Gaara",
    text_pl: "zagraj 1 kartę Gaara",
    text_ja: "我愛羅のカードを1枚出す",
    text_es: "juega 1 carta de Gaara" },
  { id: 'card-play-neji-1', level: 1, target: 1, hook: 'character.played', predicate: { targetName: 'NEJI HYÛGA' }, scope: 'cumulative',
    text_fr: "jouer 1 carte Neji Hyûga",
    text_en: "play 1 Neji Hyûga card",
    text_pt: "jogue 1 carta Neji Hyûga",
    text_it: "gioca 1 carta Neji Hyûga",
    text_pl: "zagraj 1 kartę Neji Hyûga",
    text_ja: "日向ネジのカードを1枚出す",
    text_es: "juega 1 carta de Neji Hyûga" },
  { id: 'card-play-jiraya-1', level: 1, target: 1, hook: 'character.played', predicate: { targetName: 'JIRAYA' }, scope: 'cumulative',
    text_fr: "jouer 1 carte Jiraya",
    text_en: "play 1 Jiraya card",
    text_pt: "jogue 1 carta Jiraiya",
    text_it: "gioca 1 carta Jiraiya",
    text_pl: "zagraj 1 kartę Jiraiya",
    text_ja: "自来也のカードを1枚出す",
    text_es: "juega 1 carta de Jiraya" },
  { id: 'card-play-tsunade-1', level: 1, target: 1, hook: 'character.played', predicate: { targetName: 'TSUNADE' }, scope: 'cumulative',
    text_fr: "jouer 1 carte Tsunade",
    text_en: "play 1 Tsunade card",
    text_pt: "jogue 1 carta Tsunade",
    text_it: "gioca 1 carta Tsunade",
    text_pl: "zagraj 1 kartę Tsunade",
    text_ja: "綱手のカードを1枚出す",
    text_es: "juega 1 carta de Tsunade" },
  { id: 'card-play-orochimaru-1', level: 1, target: 1, hook: 'character.played', predicate: { targetName: 'OROCHIMARU' }, scope: 'cumulative',
    text_fr: "jouer 1 carte Orochimaru",
    text_en: "play 1 Orochimaru card",
    text_pt: "jogue 1 carta Orochimaru",
    text_it: "gioca 1 carta Orochimaru",
    text_pl: "zagraj 1 kartę Orochimaru",
    text_ja: "大蛇丸のカードを1枚出す",
    text_es: "juega 1 carta de Orochimaru" },
  { id: 'play-1-leaf-village', level: 1, target: 1, hook: 'character.played.group', predicate: { group: 'Leaf Village' }, scope: 'cumulative',
    text_fr: "jouer 1 personnage du Village de la Feuille",
    text_en: "play 1 Leaf Village character",
    text_pt: "jogue 1 personagem da Vila da Folha",
    text_it: "gioca 1 personaggio del Villaggio della Foglia",
    text_pl: "zagraj 1 postać Wioski Liścia",
    text_ja: "木ノ葉隠れの里のキャラクターを1体出す",
    text_es: "juega 1 personaje de la Aldea de la Hoja" },
  { id: 'play-1-independent', level: 1, target: 1, hook: 'character.played.group', predicate: { group: 'Independent' }, scope: 'cumulative',
    text_fr: "jouer 1 personnage Indépendant",
    text_en: "play 1 Independent character",
    text_pt: "jogue 1 personagem Independente",
    text_it: "gioca 1 personaggio Indipendente",
    text_pl: "zagraj 1 postać Niezależną",
    text_ja: "独立のキャラクターを1体出す",
    text_es: "juega 1 personaje Independiente" },
  { id: 'play-1-jutsu', level: 1, target: 1, hook: 'character.played.keyword', predicate: { keyword: 'Jutsu' }, scope: 'cumulative',
    text_fr: "jouer 1 personnage avec le mot-clé Jutsu",
    text_en: "play 1 character with the Jutsu keyword",
    text_pt: "jogue 1 personagem com a palavra-chave Jutsu",
    text_it: "gioca 1 personaggio con la parola chiave Jutsu",
    text_pl: "zagraj 1 postać ze słowem kluczowym Jutsu",
    text_ja: "「術」を持つキャラクターを1体出す",
    text_es: "juega 1 personaje con la palabra clave Jutsu" },
  { id: 'play-1-team7', level: 1, target: 1, hook: 'character.played.keyword', predicate: { keyword: 'Team 7' }, scope: 'cumulative',
    text_fr: "jouer 1 personnage de la Team 7",
    text_en: "play 1 Team 7 character",
    text_pt: "jogue 1 personagem do Time 7",
    text_it: "gioca 1 personaggio della Squadra 7",
    text_pl: "zagraj 1 postać Drużyny 7",
    text_ja: "第七班のキャラクターを1体出す",
    text_es: "juega 1 personaje del Equipo 7" },
  { id: 'play-1-team8', level: 1, target: 1, hook: 'character.played.keyword', predicate: { keyword: 'Team 8' }, scope: 'cumulative',
    text_fr: "jouer 1 personnage de la Team 8",
    text_en: "play 1 Team 8 character",
    text_pt: "jogue 1 personagem do Time 8",
    text_it: "gioca 1 personaggio della Squadra 8",
    text_pl: "zagraj 1 postać Drużyny 8",
    text_ja: "第八班のキャラクターを1体出す",
    text_es: "juega 1 personaje del Equipo 8" },
  { id: 'play-1-team10', level: 1, target: 1, hook: 'character.played.keyword', predicate: { keyword: 'Team 10' }, scope: 'cumulative',
    text_fr: "jouer 1 personnage de la Team 10",
    text_en: "play 1 Team 10 character",
    text_pt: "jogue 1 personagem do Time 10",
    text_it: "gioca 1 personaggio della Squadra 10",
    text_pl: "zagraj 1 postać Drużyny 10",
    text_ja: "第十班のキャラクターを1体出す",
    text_es: "juega 1 personaje del Equipo 10" },
  { id: 'play-1-hokage', level: 1, target: 1, hook: 'character.played.keyword', predicate: { keyword: 'Hokage' }, scope: 'cumulative',
    text_fr: "jouer 1 personnage Hokage",
    text_en: "play 1 Hokage character",
    text_pt: "jogue 1 personagem Hokage",
    text_it: "gioca 1 personaggio Hokage",
    text_pl: "zagraj 1 postać Hokage",
    text_ja: "火影のキャラクターを1体出す",
    text_es: "juega 1 personaje Hokage" },
  { id: 'reveal-1-match', level: 1, target: 1, hook: 'character.revealed', scope: 'match',
    text_fr: "révéler 1 personnage caché en une partie",
    text_en: "reveal 1 hidden character in one match",
    text_pt: "revele 1 personagem oculto em uma partida",
    text_it: "rivela 1 personaggio nascosto in una partita",
    text_pl: "odkryj 1 ukrytą postać w jednym meczu",
    text_ja: "1回の対戦で伏せキャラクターを1体表にする",
    text_es: "revela a 1 personaje oculto en una partida" },
  { id: 'neji-defeat-1-match', level: 1, target: 1, hook: 'character.defeated.with.source', predicate: { sourceName: 'NEJI HYÛGA' }, scope: 'match',
    text_fr: "vaincre 1 personnage avec Neji en une partie",
    text_en: "defeat 1 character with Neji in one match",
    text_pt: "derrote 1 personagem com Neji em uma partida",
    text_it: "sconfiggi 1 personaggio con Neji in una partita",
    text_pl: "pokonaj 1 postać za pomocą Nejiego w jednym meczu",
    text_ja: "1回の対戦で日向ネジでキャラクターを1体撃破する",
    text_es: "derrota a 1 personaje con Neji en una partida" },
  { id: 'kabuto-hide-1-match', level: 1, target: 1, hook: 'character.hidden.with.source', predicate: { sourceName: 'KABUTO YAKUSHI' }, scope: 'match',
    text_fr: "cacher 1 personnage avec Kabuto en une partie",
    text_en: "hide 1 character with Kabuto in one match",
    text_pt: "oculte 1 personagem com Kabuto em uma partida",
    text_it: "nascondi 1 personaggio con Kabuto in una partita",
    text_pl: "ukryj 1 postać za pomocą Kabuto w jednym meczu",
    text_ja: "1回の対戦で薬師カブトでキャラクターを1体伏せる",
    text_es: "oculta a 1 personaje con Kabuto en una partida" },

  { id: 'card-play-naruto-5', level: 2, target: 5, hook: 'character.played', predicate: { targetName: 'NARUTO UZUMAKI' }, scope: 'cumulative',
    text_fr: "jouer 5 cartes Naruto Uzumaki au total",
    text_en: "play 5 Naruto Uzumaki cards in total",
    text_pt: "jogue 5 cartas Naruto Uzumaki no total",
    text_it: "gioca 5 carte Naruto Uzumaki in totale",
    text_pl: "zagraj 5 kart Naruto Uzumaki łącznie",
    text_ja: "うずまきナルトのカードを合計5枚出す",
    text_es: "juega 5 cartas de Naruto Uzumaki en total" },
  { id: 'card-play-kakashi-5', level: 2, target: 5, hook: 'character.played', predicate: { targetName: 'KAKASHI HATAKE' }, scope: 'cumulative',
    text_fr: "jouer 5 cartes Kakashi Hatake au total",
    text_en: "play 5 Kakashi Hatake cards in total",
    text_pt: "jogue 5 cartas Kakashi Hatake no total",
    text_it: "gioca 5 carte Kakashi Hatake in totale",
    text_pl: "zagraj 5 kart Kakashi Hatake łącznie",
    text_ja: "はたけカカシのカードを合計5枚出す",
    text_es: "juega 5 cartas de Kakashi Hatake en total" },
  { id: 'card-play-sasuke-5', level: 2, target: 5, hook: 'character.played', predicate: { targetName: 'SASUKE UCHIWA' }, scope: 'cumulative',
    text_fr: "jouer 5 cartes Sasuke Uchiwa au total",
    text_en: "play 5 Sasuke Uchiwa cards in total",
    text_pt: "jogue 5 cartas Sasuke Uchiha no total",
    text_it: "gioca 5 carte Sasuke Uchiha in totale",
    text_pl: "zagraj 5 kart Sasuke Uchiha łącznie",
    text_ja: "うちはサスケのカードを合計5枚出す",
    text_es: "juega 5 cartas de Sasuke Uchiwa en total" },
  { id: 'kidomaru-defeat-3-match', level: 2, target: 3, hook: 'character.defeated.with.source', predicate: { sourceName: 'KIDÔMARU' }, scope: 'match',
    text_fr: "vaincre 3 personnages avec Kidômaru en une partie",
    text_en: "defeat 3 characters with Kidômaru in one match",
    text_pt: "derrote 3 personagens com Kidômaru em uma partida",
    text_it: "sconfiggi 3 personaggi con Kidômaru in una partita",
    text_pl: "pokonaj 3 postacie za pomocą Kidômaru w jednym meczu",
    text_ja: "1回の対戦で鬼童丸でキャラクターを3体撃破する",
    text_es: "derrota a 3 personajes con Kidômaru en una partida" },
  { id: 'tenten-defeat-hidden-3', level: 2, target: 3, hook: 'character.defeated.hidden.with.source', predicate: { sourceName: 'TENTEN' }, scope: 'cumulative',
    text_fr: "vaincre 3 personnages cachés avec Tenten",
    text_en: "defeat 3 hidden characters with Tenten",
    text_pt: "derrote 3 personagens ocultos com Tenten",
    text_it: "sconfiggi 3 personaggi nascosti con Tenten",
    text_pl: "pokonaj 3 ukryte postacie za pomocą Tenten",
    text_ja: "テンテンで伏せキャラクターを3体撃破する",
    text_es: "derrota a 3 personajes ocultos con Tenten" },
  { id: 'kiba-hide-3-match', level: 2, target: 3, hook: 'character.hidden.with.source', predicate: { sourceName: 'KIBA INUZUKA' }, scope: 'match',
    text_fr: "cacher 3 personnages avec Kiba en une partie",
    text_en: "hide 3 characters with Kiba in one match",
    text_pt: "oculte 3 personagens com Kiba em uma partida",
    text_it: "nascondi 3 personaggi con Kiba in una partita",
    text_pl: "ukryj 3 postacie za pomocą Kiby w jednym meczu",
    text_ja: "1回の対戦で犬塚キバでキャラクターを3体伏せる",
    text_es: "oculta a 3 personajes con Kiba en una partida" },
  { id: 'zabuza-hide-5', level: 2, target: 5, hook: 'character.hidden.with.source', predicate: { sourceName: 'ZABUZA MOMOCHI' }, scope: 'cumulative',
    text_fr: "cacher 5 personnages avec Zabuza",
    text_en: "hide 5 characters with Zabuza",
    text_pt: "oculte 5 personagens com Zabuza",
    text_it: "nascondi 5 personaggi con Zabuza",
    text_pl: "ukryj 5 postaci za pomocą Zabuzy",
    text_ja: "桃地再不斬でキャラクターを5体伏せる",
    text_es: "oculta a 5 personajes con Zabuza" },
  { id: 'ino-control-2-match', level: 2, target: 2, hook: 'character.controlled.with.source', predicate: { sourceName: 'INO YAMANAKA' }, scope: 'match',
    text_fr: "prendre le contrôle de 2 personnages avec Ino en une partie",
    text_en: "take control of 2 characters with Ino in one match",
    text_pt: "assuma o controle de 2 personagens com Ino em uma partida",
    text_it: "prendi il controllo di 2 personaggi con Ino in una partita",
    text_pl: "przejmij kontrolę nad 2 postaciami za pomocą Ino w jednym meczu",
    text_ja: "1回の対戦で山中いのでキャラクターを2体コントロールする",
    text_es: "toma el control de 2 personajes con Ino en una partida" },
  { id: 'ebisu-draw-3-match', level: 2, target: 3, hook: 'card.drawn.via_effect.source', predicate: { sourceName: 'EBISU' }, scope: 'match',
    text_fr: "piocher 3 cartes avec Ebisu en une partie",
    text_en: "draw 3 cards with Ebisu in one match",
    text_pt: "compre 3 cartas com Ebisu em uma partida",
    text_it: "pesca 3 carte con Ebisu in una partita",
    text_pl: "dobierz 3 karty za pomocą Ebisu w jednym meczu",
    text_ja: "1回の対戦でエビスでカードを3枚引く",
    text_es: "roba 3 cartas con Ebisu en una partida" },
  { id: 'manda-defeat-3', level: 2, target: 3, hook: 'character.defeated.with.source', predicate: { sourceName: 'MANDA' }, scope: 'cumulative',
    text_fr: "vaincre 3 Invocations adverses avec Manda",
    text_en: "defeat 3 enemy Summons with Manda",
    text_pt: "derrote 3 Invocações inimigas com Manda",
    text_it: "sconfiggi 3 Evocazioni nemiche con Manda",
    text_pl: "pokonaj 3 wrogie Przywołania za pomocą Mandy",
    text_ja: "マンダで敵の口寄せを3体撃破する",
    text_es: "derrota a 3 Invocaciones enemigas con Manda" },
  { id: 'anko-defeat-3', level: 2, target: 3, hook: 'character.defeated.with.source', predicate: { sourceName: 'ANKO MITARASHI' }, scope: 'cumulative',
    text_fr: "vaincre 3 personnages cachés adverses avec Anko",
    text_en: "defeat 3 enemy hidden characters with Anko",
    text_pt: "derrote 3 personagens inimigos ocultos com Anko",
    text_it: "sconfiggi 3 personaggi nemici nascosti con Anko",
    text_pl: "pokonaj 3 wrogie ukryte postacie za pomocą Anko",
    text_ja: "みたらしアンコで敵の伏せキャラクターを3体撃破する",
    text_es: "derrota a 3 personajes enemigos ocultos con Anko" },
  { id: 'orochimaru-defeat-3', level: 2, target: 3, hook: 'character.defeated.with.source', predicate: { sourceName: 'OROCHIMARU' }, scope: 'cumulative',
    text_fr: "vaincre 3 personnages cachés adverses avec Orochimaru",
    text_en: "defeat 3 enemy hidden characters with Orochimaru",
    text_pt: "derrote 3 personagens inimigos ocultos com Orochimaru",
    text_it: "sconfiggi 3 personaggi nemici nascosti con Orochimaru",
    text_pl: "pokonaj 3 wrogie ukryte postacie za pomocą Orochimaru",
    text_ja: "大蛇丸で敵の伏せキャラクターを3体撃破する",
    text_es: "derrota a 3 personajes enemigos ocultos con Orochimaru" },
  { id: 'baki-defeat-3', level: 2, target: 3, hook: 'character.defeated.with.source', predicate: { sourceName: 'BAKI' }, scope: 'cumulative',
    text_fr: "vaincre 3 personnages avec Baki",
    text_en: "defeat 3 characters with Baki",
    text_pt: "derrote 3 personagens com Baki",
    text_it: "sconfiggi 3 personaggi con Baki",
    text_pl: "pokonaj 3 postacie za pomocą Bakiego",
    text_ja: "バキでキャラクターを3体撃破する",
    text_es: "derrota a 3 personajes con Baki" },
  { id: 'temari-move-3-match', level: 2, target: 3, hook: 'character.moved.with.source', predicate: { sourceName: 'TEMARI', friendly: true }, scope: 'match',
    text_fr: "déplacer 3 alliés avec Temari en une partie",
    text_en: "move 3 allies with Temari in one match",
    text_pt: "mova 3 aliados com Temari em uma partida",
    text_it: "sposta 3 alleati con Temari in una partita",
    text_pl: "przenieś 3 sojuszników za pomocą Temari w jednym meczu",
    text_ja: "1回の対戦でテマリで味方を3体移動させる",
    text_es: "mueve a 3 aliados con Temari en una partida" },
  { id: 'play-10-leaf-village', level: 2, target: 10, hook: 'character.played.group', predicate: { group: 'Leaf Village' }, scope: 'cumulative',
    text_fr: "jouer 10 personnages du Village de la Feuille",
    text_en: "play 10 Leaf Village characters",
    text_pt: "jogue 10 personagens da Vila da Folha",
    text_it: "gioca 10 personaggi del Villaggio della Foglia",
    text_pl: "zagraj 10 postaci Wioski Liścia",
    text_ja: "木ノ葉隠れの里のキャラクターを10体出す",
    text_es: "juega 10 personajes de la Aldea de la Hoja" },
  { id: 'play-10-sand-village', level: 2, target: 10, hook: 'character.played.group', predicate: { group: 'Sand Village' }, scope: 'cumulative',
    text_fr: "jouer 10 personnages du Village du Sable",
    text_en: "play 10 Sand Village characters",
    text_pt: "jogue 10 personagens da Vila da Areia",
    text_it: "gioca 10 personaggi del Villaggio della Sabbia",
    text_pl: "zagraj 10 postaci Wioski Piasku",
    text_ja: "砂隠れの里のキャラクターを10体出す",
    text_es: "juega 10 personajes de la Aldea de la Arena" },
  { id: 'play-10-sound-village', level: 2, target: 10, hook: 'character.played.group', predicate: { group: 'Sound Village' }, scope: 'cumulative',
    text_fr: "jouer 10 personnages du Village du Son",
    text_en: "play 10 Sound Village characters",
    text_pt: "jogue 10 personagens da Vila do Som",
    text_it: "gioca 10 personaggi del Villaggio del Suono",
    text_pl: "zagraj 10 postaci Wioski Dźwięku",
    text_ja: "音隠れの里のキャラクターを10体出す",
    text_es: "juega 10 personajes de la Aldea del Sonido" },
  { id: 'play-10-akatsuki', level: 2, target: 10, hook: 'character.played.group', predicate: { group: 'Akatsuki' }, scope: 'cumulative',
    text_fr: "jouer 10 personnages Akatsuki",
    text_en: "play 10 Akatsuki characters",
    text_pt: "jogue 10 personagens da Akatsuki",
    text_it: "gioca 10 personaggi dell'Akatsuki",
    text_pl: "zagraj 10 postaci Akatsuki",
    text_ja: "暁のキャラクターを10体出す",
    text_es: "juega 10 personajes de Akatsuki" },
  { id: 'play-5-sannin', level: 2, target: 5, hook: 'character.played.keyword', predicate: { keyword: 'Sannin' }, scope: 'cumulative',
    text_fr: "jouer 5 personnages Sannin",
    text_en: "play 5 Sannin characters",
    text_pt: "jogue 5 personagens Sannin",
    text_it: "gioca 5 personaggi Sannin",
    text_pl: "zagraj 5 postaci Sannin",
    text_ja: "三忍のキャラクターを5体出す",
    text_es: "juega 5 personajes Sannin" },
  { id: 'play-5-summon', level: 2, target: 5, hook: 'character.played.keyword', predicate: { keyword: 'Summon' }, scope: 'cumulative',
    text_fr: "jouer 5 personnages Invocation",
    text_en: "play 5 Summon characters",
    text_pt: "jogue 5 personagens de Invocação",
    text_it: "gioca 5 personaggi Evocazione",
    text_pl: "zagraj 5 postaci Przywołania",
    text_ja: "口寄せのキャラクターを5体出す",
    text_es: "juega 5 personajes de Invocación" },

  { id: 'kidomaru-defeat-15', level: 3, target: 15, hook: 'character.defeated.with.source', predicate: { sourceName: 'KIDÔMARU' }, scope: 'cumulative',
    text_fr: "vaincre 15 personnages avec Kidômaru au total",
    text_en: "defeat 15 characters with Kidômaru in total",
    text_pt: "derrote 15 personagens com Kidômaru no total",
    text_it: "sconfiggi 15 personaggi con Kidômaru in totale",
    text_pl: "pokonaj 15 postaci za pomocą Kidômaru łącznie",
    text_ja: "鬼童丸でキャラクターを合計15体撃破する",
    text_es: "derrota a 15 personajes con Kidômaru en total" },
  { id: 'tenten-defeat-hidden-10', level: 3, target: 10, hook: 'character.defeated.hidden.with.source', predicate: { sourceName: 'TENTEN' }, scope: 'cumulative',
    text_fr: "vaincre 10 personnages cachés avec Tenten au total",
    text_en: "defeat 10 hidden characters with Tenten in total",
    text_pt: "derrote 10 personagens ocultos com Tenten no total",
    text_it: "sconfiggi 10 personaggi nascosti con Tenten in totale",
    text_pl: "pokonaj 10 ukrytych postaci za pomocą Tenten łącznie",
    text_ja: "テンテンで伏せキャラクターを合計10体撃破する",
    text_es: "derrota a 10 personajes ocultos con Tenten en total" },
  { id: 'kabuto-hide-10', level: 3, target: 10, hook: 'character.hidden.with.source', predicate: { sourceName: 'KABUTO YAKUSHI' }, scope: 'cumulative',
    text_fr: "cacher 10 personnages avec Kabuto au total",
    text_en: "hide 10 characters with Kabuto in total",
    text_pt: "oculte 10 personagens com Kabuto no total",
    text_it: "nascondi 10 personaggi con Kabuto in totale",
    text_pl: "ukryj 10 postaci za pomocą Kabuto łącznie",
    text_ja: "薬師カブトでキャラクターを合計10体伏せる",
    text_es: "oculta a 10 personajes con Kabuto en total" },
  { id: 'kiba-hide-10', level: 3, target: 10, hook: 'character.hidden.with.source', predicate: { sourceName: 'KIBA INUZUKA' }, scope: 'cumulative',
    text_fr: "cacher 10 personnages avec Kiba au total",
    text_en: "hide 10 characters with Kiba in total",
    text_pt: "oculte 10 personagens com Kiba no total",
    text_it: "nascondi 10 personaggi con Kiba in totale",
    text_pl: "ukryj 10 postaci za pomocą Kiby łącznie",
    text_ja: "犬塚キバでキャラクターを合計10体伏せる",
    text_es: "oculta a 10 personajes con Kiba en total" },
  { id: 'zabuza-hide-5-match', level: 3, target: 5, hook: 'character.hidden.with.source', predicate: { sourceName: 'ZABUZA MOMOCHI' }, scope: 'match',
    text_fr: "cacher 5 personnages avec Zabuza en une partie",
    text_en: "hide 5 characters with Zabuza in one match",
    text_pt: "oculte 5 personagens com Zabuza em uma partida",
    text_it: "nascondi 5 personaggi con Zabuza in una partita",
    text_pl: "ukryj 5 postaci za pomocą Zabuzy w jednym meczu",
    text_ja: "1回の対戦で桃地再不斬でキャラクターを5体伏せる",
    text_es: "oculta a 5 personajes con Zabuza en una partida" },
  { id: 'ino-control-10', level: 3, target: 10, hook: 'character.controlled.with.source', predicate: { sourceName: 'INO YAMANAKA' }, scope: 'cumulative',
    text_fr: "prendre le contrôle de 10 personnages avec Ino au total",
    text_en: "take control of 10 characters with Ino in total",
    text_pt: "assuma o controle de 10 personagens com Ino no total",
    text_it: "prendi il controllo di 10 personaggi con Ino in totale",
    text_pl: "przejmij kontrolę nad 10 postaciami za pomocą Ino łącznie",
    text_ja: "山中いのでキャラクターを合計10体コントロールする",
    text_es: "toma el control de 10 personajes con Ino en total" },
  { id: 'ebisu-draw-10', level: 3, target: 10, hook: 'card.drawn.via_effect.source', predicate: { sourceName: 'EBISU' }, scope: 'cumulative',
    text_fr: "piocher 10 cartes avec Ebisu au total",
    text_en: "draw 10 cards with Ebisu in total",
    text_pt: "compre 10 cartas com Ebisu no total",
    text_it: "pesca 10 carte con Ebisu in totale",
    text_pl: "dobierz 10 kart za pomocą Ebisu łącznie",
    text_ja: "エビスでカードを合計10枚引く",
    text_es: "roba 10 cartas con Ebisu en total" },
  { id: 'kakashi-copy-10', level: 3, target: 10, hook: 'effect.copied.with.source', predicate: { sourceName: 'KAKASHI HATAKE' }, scope: 'cumulative',
    text_fr: "copier 10 effets avec Kakashi au total",
    text_en: "copy 10 effects with Kakashi in total",
    text_pt: "copie 10 efeitos com Kakashi no total",
    text_it: "copia 10 effetti con Kakashi in totale",
    text_pl: "skopiuj 10 efektów za pomocą Kakashiego łącznie",
    text_ja: "はたけカカシで効果を合計10回コピーする",
    text_es: "copia 10 efectos con Kakashi en total" },
  { id: 'sakon-copy-10', level: 3, target: 10, hook: 'effect.copied.with.source', predicate: { sourceName: 'SAKON' }, scope: 'cumulative',
    text_fr: "copier 10 effets avec Sakon au total",
    text_en: "copy 10 effects with Sakon in total",
    text_pt: "copie 10 efeitos com Sakon no total",
    text_it: "copia 10 effetti con Sakon in totale",
    text_pl: "skopiuj 10 efektów za pomocą Sakona łącznie",
    text_ja: "左近で効果を合計10回コピーする",
    text_es: "copia 10 efectos con Sakon en total" },
  { id: 'neji-remove-20', level: 3, target: 20, hook: 'tokens.removed.with.source', predicate: { sourceName: 'NEJI HYÛGA' }, scope: 'cumulative',
    text_fr: "retirer 20 jetons de Puissance avec Neji au total",
    text_en: "remove 20 Power tokens with Neji in total",
    text_pt: "remova 20 fichas de Poder com Neji no total",
    text_it: "rimuovi 20 token Potenza con Neji in totale",
    text_pl: "usuń 20 żetonów Siły za pomocą Nejiego łącznie",
    text_ja: "日向ネジでパワートークンを合計20個取り除く",
    text_es: "retira 20 fichas de Poder con Neji en total" },
  { id: 'kisame-remove-15', level: 3, target: 15, hook: 'tokens.removed.with.source', predicate: { sourceName: 'KISAME HOSHIGAKI' }, scope: 'cumulative',
    text_fr: "retirer 15 jetons de Puissance avec Kisame au total",
    text_en: "remove 15 Power tokens with Kisame in total",
    text_pt: "remova 15 fichas de Poder com Kisame no total",
    text_it: "rimuovi 15 token Potenza con Kisame in totale",
    text_pl: "usuń 15 żetonów Siły za pomocą Kisame łącznie",
    text_ja: "干柿鬼鮫でパワートークンを合計15個取り除く",
    text_es: "retira 15 fichas de Poder con Kisame en total" },
  { id: 'hiruzen-reduce-10', level: 3, target: 10, hook: 'cost_reduction.with.source', predicate: { sourceName: 'HIRUZEN SARUTOBI', targetGroup: 'Leaf Village' }, scope: 'cumulative',
    text_fr: "réduire 10 fois le coût d'un personnage du Village de la Feuille avec Hiruzen",
    text_en: "reduce a Leaf Village character's cost 10 times with Hiruzen",
    text_pt: "reduza o custo de um personagem da Vila da Folha 10 vezes com Hiruzen",
    text_it: "riduci il costo di un personaggio del Villaggio della Foglia 10 volte con Hiruzen",
    text_pl: "obniż koszt postaci Wioski Liścia 10 razy za pomocą Hiruzena",
    text_ja: "猿飛ヒルゼンで木ノ葉隠れの里のキャラクターのコストを10回下げる",
    text_es: "reduce el coste de un personaje de la Aldea de la Hoja 10 veces con Hiruzen" },
  { id: 'sasuke-ambush-10', level: 3, target: 10, hook: 'ambush.activated.with.source', predicate: { sourceName: 'SASUKE UCHIWA' }, scope: 'cumulative',
    text_fr: "déclencher l'AMBUSH de Sasuke 10 fois",
    text_en: "trigger Sasuke's AMBUSH 10 times",
    text_pt: "ative o AMBUSH de Sasuke 10 vezes",
    text_it: "attiva l'AMBUSH di Sasuke 10 volte",
    text_pl: "aktywuj AMBUSH Sasuke 10 razy",
    text_ja: "うちはサスケのAMBUSHを10回発動する",
    text_es: "activa el AMBUSH de Sasuke 10 veces" },
  { id: 'asuma-ambush-5', level: 3, target: 5, hook: 'ambush.activated.with.source', predicate: { sourceName: 'ASUMA SARUTOBI' }, scope: 'cumulative',
    text_fr: "déclencher l'AMBUSH d'Asuma 5 fois",
    text_en: "trigger Asuma's AMBUSH 5 times",
    text_pt: "ative o AMBUSH de Asuma 5 vezes",
    text_it: "attiva l'AMBUSH di Asuma 5 volte",
    text_pl: "aktywuj AMBUSH Asumy 5 razy",
    text_ja: "猿飛アスマのAMBUSHを5回発動する",
    text_es: "activa el AMBUSH de Asuma 5 veces" },
  { id: 'reveal-ambush-5-match', level: 3, target: 5, hook: 'ambush.activated.via_reveal', scope: 'match',
    text_fr: "révéler 5 cartes pour déclencher leur AMBUSH en une partie",
    text_en: "reveal 5 cards to trigger their AMBUSH in one match",
    text_pt: "revele 5 cartas para ativar seu AMBUSH em uma partida",
    text_it: "rivela 5 carte per attivare il loro AMBUSH in una partita",
    text_pl: "odkryj 5 kart, aby aktywować ich AMBUSH w jednym meczu",
    text_ja: "1回の対戦で5枚のカードを表にしてAMBUSHを発動する",
    text_es: "revela 5 cartas para activar su AMBUSH en una partida" },
  { id: 'kakashi-power-10', level: 3, target: 1, hook: 'character.power.threshold', predicate: { name: 'KAKASHI HATAKE', threshold: 10 }, scope: 'match',
    text_fr: "avoir un Kakashi à 10 Puissance ou plus en une partie",
    text_en: "have a Kakashi with 10 or more Power in one match",
    text_pt: "tenha um Kakashi com 10 ou mais de Poder em uma partida",
    text_it: "abbi un Kakashi con 10 o più Potenza in una partita",
    text_pl: "miej Kakashiego z 10 lub więcej Siły w jednym meczu",
    text_ja: "1回の対戦ではたけカカシをパワー10以上にする",
    text_es: "ten un Kakashi con 10 o más de Poder en una partida" },
  { id: 'sasuke-power-10', level: 3, target: 1, hook: 'character.power.threshold', predicate: { name: 'SASUKE UCHIWA', threshold: 10 }, scope: 'match',
    text_fr: "avoir un Sasuke à 10 Puissance ou plus en une partie",
    text_en: "have a Sasuke with 10 or more Power in one match",
    text_pt: "tenha um Sasuke com 10 ou mais de Poder em uma partida",
    text_it: "abbi un Sasuke con 10 o più Potenza in una partita",
    text_pl: "miej Sasuke z 10 lub więcej Siły w jednym meczu",
    text_ja: "1回の対戦でうちはサスケをパワー10以上にする",
    text_es: "ten un Sasuke con 10 o más de Poder en una partida" },
  { id: 'naruto-tokens-10', level: 3, target: 1, hook: 'character.power_tokens.threshold', predicate: { name: 'NARUTO UZUMAKI', threshold: 10 }, scope: 'match',
    text_fr: "avoir un Naruto avec 10 jetons de Puissance ou plus en une partie",
    text_en: "have a Naruto with 10 or more Power tokens in one match",
    text_pt: "tenha um Naruto com 10 ou mais fichas de Poder em uma partida",
    text_it: "abbi un Naruto con 10 o più token Potenza in una partita",
    text_pl: "miej Naruto z 10 lub więcej żetonami Siły w jednym meczu",
    text_ja: "1回の対戦でうずまきナルトにパワートークンを10個以上持たせる",
    text_es: "ten un Naruto con 10 o más fichas de Poder en una partida" },
  { id: 'gaara-tokens-10', level: 3, target: 1, hook: 'character.power_tokens.threshold', predicate: { name: 'GAARA', threshold: 10 }, scope: 'match',
    text_fr: "avoir un Gaara avec 10 jetons de Puissance ou plus en une partie",
    text_en: "have a Gaara with 10 or more Power tokens in one match",
    text_pt: "tenha um Gaara com 10 ou mais fichas de Poder em uma partida",
    text_it: "abbi un Gaara con 10 o più token Potenza in una partita",
    text_pl: "miej Gaarę z 10 lub więcej żetonami Siły w jednym meczu",
    text_ja: "1回の対戦で我愛羅にパワートークンを10個以上持たせる",
    text_es: "ten un Gaara con 10 o más fichas de Poder en una partida" },
  { id: 'mission-naruto-jiraya', level: 3, target: 1, hook: 'mission.has.characters', predicate: { names: ['NARUTO UZUMAKI', 'JIRAYA'] }, scope: 'match',
    text_fr: "avoir Naruto et Jiraya sur la même mission en une partie",
    text_en: "have Naruto and Jiraya on the same mission in one match",
    text_pt: "tenha Naruto e Jiraiya na mesma missão em uma partida",
    text_it: "abbi Naruto e Jiraiya nella stessa missione in una partita",
    text_pl: "miej Naruto i Jiraiyę na tej samej misji w jednym meczu",
    text_ja: "1回の対戦でうずまきナルトと自来也を同じミッションに揃える",
    text_es: "ten a Naruto y a Jiraya en la misma misión en una partida" },

  { id: 'kidomaru-defeat-50', level: 4, target: 50, hook: 'character.defeated.with.source', predicate: { sourceName: 'KIDÔMARU' }, scope: 'cumulative',
    text_fr: "vaincre 50 personnages avec Kidômaru au total",
    text_en: "defeat 50 characters with Kidômaru in total",
    text_pt: "derrote 50 personagens com Kidômaru no total",
    text_it: "sconfiggi 50 personaggi con Kidômaru in totale",
    text_pl: "pokonaj 50 postaci za pomocą Kidômaru łącznie",
    text_ja: "鬼童丸でキャラクターを合計50体撃破する",
    text_es: "derrota a 50 personajes con Kidômaru en total" },
  { id: 'kabuto-hide-50', level: 4, target: 50, hook: 'character.hidden.with.source', predicate: { sourceName: 'KABUTO YAKUSHI' }, scope: 'cumulative',
    text_fr: "cacher 50 personnages avec Kabuto au total",
    text_en: "hide 50 characters with Kabuto in total",
    text_pt: "oculte 50 personagens com Kabuto no total",
    text_it: "nascondi 50 personaggi con Kabuto in totale",
    text_pl: "ukryj 50 postaci za pomocą Kabuto łącznie",
    text_ja: "薬師カブトでキャラクターを合計50体伏せる",
    text_es: "oculta a 50 personajes con Kabuto en total" },
  { id: 'kiba-hide-30', level: 4, target: 30, hook: 'character.hidden.with.source', predicate: { sourceName: 'KIBA INUZUKA' }, scope: 'cumulative',
    text_fr: "cacher 30 personnages avec Kiba au total",
    text_en: "hide 30 characters with Kiba in total",
    text_pt: "oculte 30 personagens com Kiba no total",
    text_it: "nascondi 30 personaggi con Kiba in totale",
    text_pl: "ukryj 30 postaci za pomocą Kiby łącznie",
    text_ja: "犬塚キバでキャラクターを合計30体伏せる",
    text_es: "oculta a 30 personajes con Kiba en total" },
  { id: 'ino-control-25', level: 4, target: 25, hook: 'character.controlled.with.source', predicate: { sourceName: 'INO YAMANAKA' }, scope: 'cumulative',
    text_fr: "prendre le contrôle de 25 personnages avec Ino au total",
    text_en: "take control of 25 characters with Ino in total",
    text_pt: "assuma o controle de 25 personagens com Ino no total",
    text_it: "prendi il controllo di 25 personaggi con Ino in totale",
    text_pl: "przejmij kontrolę nad 25 postaciami za pomocą Ino łącznie",
    text_ja: "山中いのでキャラクターを合計25体コントロールする",
    text_es: "toma el control de 25 personajes con Ino en total" },
  { id: 'kakashi-copy-50', level: 4, target: 50, hook: 'effect.copied.with.source', predicate: { sourceName: 'KAKASHI HATAKE' }, scope: 'cumulative',
    text_fr: "copier 50 effets avec Kakashi au total",
    text_en: "copy 50 effects with Kakashi in total",
    text_pt: "copie 50 efeitos com Kakashi no total",
    text_it: "copia 50 effetti con Kakashi in totale",
    text_pl: "skopiuj 50 efektów za pomocą Kakashiego łącznie",
    text_ja: "はたけカカシで効果を合計50回コピーする",
    text_es: "copia 50 efectos con Kakashi en total" },
  { id: 'neji-remove-75', level: 4, target: 75, hook: 'tokens.removed.with.source', predicate: { sourceName: 'NEJI HYÛGA' }, scope: 'cumulative',
    text_fr: "retirer 75 jetons de Puissance avec Neji au total",
    text_en: "remove 75 Power tokens with Neji in total",
    text_pt: "remova 75 fichas de Poder com Neji no total",
    text_it: "rimuovi 75 token Potenza con Neji in totale",
    text_pl: "usuń 75 żetonów Siły za pomocą Nejiego łącznie",
    text_ja: "日向ネジでパワートークンを合計75個取り除く",
    text_es: "retira 75 fichas de Poder con Neji en total" },
  { id: 'tenten-defeat-hidden-10-match', level: 4, target: 10, hook: 'character.defeated.hidden.with.source', predicate: { sourceName: 'TENTEN' }, scope: 'match',
    text_fr: "vaincre 10 personnages cachés avec Tenten en une seule partie",
    text_en: "defeat 10 hidden characters with Tenten in a single match",
    text_pt: "derrote 10 personagens ocultos com Tenten em uma única partida",
    text_it: "sconfiggi 10 personaggi nascosti con Tenten in una singola partita",
    text_pl: "pokonaj 10 ukrytych postaci za pomocą Tenten w jednym meczu",
    text_ja: "1回の対戦でテンテンで伏せキャラクターを10体撃破する",
    text_es: "derrota a 10 personajes ocultos con Tenten en una sola partida" },
  { id: 'mission-akatsuki-trio', level: 4, target: 1, hook: 'mission.has.characters', predicate: { names: ['ITACHI UCHIWA', 'SASUKE UCHIWA', 'KISAME HOSHIGAKI'] }, scope: 'match',
    text_fr: "avoir Itachi, Sasuke et Kisame sur la même mission",
    text_en: "have Itachi, Sasuke and Kisame on the same mission",
    text_pt: "tenha Itachi, Sasuke e Kisame na mesma missão",
    text_it: "abbi Itachi, Sasuke e Kisame nella stessa missione",
    text_pl: "miej Itachiego, Sasuke i Kisame na tej samej misji",
    text_ja: "うちはイタチ、うちはサスケ、干柿鬼鮫を同じミッションに揃える",
    text_es: "ten a Itachi, Sasuke y Kisame en la misma misión" },
  { id: 'mission-team7-plus-kakashi', level: 4, target: 1, hook: 'mission.has.characters', predicate: { names: ['NARUTO UZUMAKI', 'SAKURA HARUNO', 'SASUKE UCHIWA', 'KAKASHI HATAKE'] }, scope: 'match',
    text_fr: "avoir Naruto, Sakura, Sasuke et Kakashi sur la même mission",
    text_en: "have Naruto, Sakura, Sasuke and Kakashi on the same mission",
    text_pt: "tenha Naruto, Sakura, Sasuke e Kakashi na mesma missão",
    text_it: "abbi Naruto, Sakura, Sasuke e Kakashi nella stessa missione",
    text_pl: "miej Naruto, Sakurę, Sasuke i Kakashiego na tej samej misji",
    text_ja: "うずまきナルト、春野サクラ、うちはサスケ、はたけカカシを同じミッションに揃える",
    text_es: "ten a Naruto, Sakura, Sasuke y Kakashi en la misma misión" },
  { id: 'play-50-leaf-village', level: 4, target: 50, hook: 'character.played.group', predicate: { group: 'Leaf Village' }, scope: 'cumulative',
    text_fr: "jouer 50 personnages du Village de la Feuille au total",
    text_en: "play 50 Leaf Village characters in total",
    text_pt: "jogue 50 personagens da Vila da Folha no total",
    text_it: "gioca 50 personaggi del Villaggio della Foglia in totale",
    text_pl: "zagraj 50 postaci Wioski Liścia łącznie",
    text_ja: "木ノ葉隠れの里のキャラクターを合計50体出す",
    text_es: "juega 50 personajes de la Aldea de la Hoja en total" },
  { id: 'play-50-akatsuki', level: 4, target: 50, hook: 'character.played.group', predicate: { group: 'Akatsuki' }, scope: 'cumulative',
    text_fr: "jouer 50 personnages Akatsuki au total",
    text_en: "play 50 Akatsuki characters in total",
    text_pt: "jogue 50 personagens da Akatsuki no total",
    text_it: "gioca 50 personaggi dell'Akatsuki in totale",
    text_pl: "zagraj 50 postaci Akatsuki łącznie",
    text_ja: "暁のキャラクターを合計50体出す",
    text_es: "juega 50 personajes de Akatsuki en total" },
  { id: 'play-50-sound-village', level: 4, target: 50, hook: 'character.played.group', predicate: { group: 'Sound Village' }, scope: 'cumulative',
    text_fr: "jouer 50 personnages du Village du Son au total",
    text_en: "play 50 Sound Village characters in total",
    text_pt: "jogue 50 personagens da Vila do Som no total",
    text_it: "gioca 50 personaggi del Villaggio del Suono in totale",
    text_pl: "zagraj 50 postaci Wioski Dźwięku łącznie",
    text_ja: "音隠れの里のキャラクターを合計50体出す",
    text_es: "juega 50 personajes de la Aldea del Sonido en total" },
  { id: 'play-50-sand-village', level: 4, target: 50, hook: 'character.played.group', predicate: { group: 'Sand Village' }, scope: 'cumulative',
    text_fr: "jouer 50 personnages du Village du Sable au total",
    text_en: "play 50 Sand Village characters in total",
    text_pt: "jogue 50 personagens da Vila da Areia no total",
    text_it: "gioca 50 personaggi del Villaggio della Sabbia in totale",
    text_pl: "zagraj 50 postaci Wioski Piasku łącznie",
    text_ja: "砂隠れの里のキャラクターを合計50体出す",
    text_es: "juega 50 personajes de la Aldea de la Arena en total" },
  { id: 'play-25-summon', level: 4, target: 25, hook: 'character.played.keyword', predicate: { keyword: 'Summon' }, scope: 'cumulative',
    text_fr: "jouer 25 personnages Invocation au total",
    text_en: "play 25 Summon characters in total",
    text_pt: "jogue 25 personagens de Invocação no total",
    text_it: "gioca 25 personaggi Evocazione in totale",
    text_pl: "zagraj 25 postaci Przywołania łącznie",
    text_ja: "口寄せのキャラクターを合計25体出す",
    text_es: "juega 25 personajes de Invocación en total" },
  { id: 'play-25-sannin', level: 4, target: 25, hook: 'character.played.keyword', predicate: { keyword: 'Sannin' }, scope: 'cumulative',
    text_fr: "jouer 25 personnages Sannin au total",
    text_en: "play 25 Sannin characters in total",
    text_pt: "jogue 25 personagens Sannin no total",
    text_it: "gioca 25 personaggi Sannin in totale",
    text_pl: "zagraj 25 postaci Sannin łącznie",
    text_ja: "三忍のキャラクターを合計25体出す",
    text_es: "juega 25 personajes Sannin en total" },
  { id: 'rock-lee-tokens-15', level: 4, target: 1, hook: 'character.power_tokens.threshold', predicate: { name: 'ROCK LEE', threshold: 15 }, scope: 'match',
    text_fr: "avoir un Rock Lee avec 15 jetons de Puissance ou plus en une partie",
    text_en: "have a Rock Lee with 15 or more Power tokens in one match",
    text_pt: "tenha um Rock Lee com 15 ou mais fichas de Poder em uma partida",
    text_it: "abbi un Rock Lee con 15 o più token Potenza in una partita",
    text_pl: "miej Rocka Lee z 15 lub więcej żetonami Siły w jednym meczu",
    text_ja: "1回の対戦でロック・リーにパワートークンを15個以上持たせる",
    text_es: "ten un Rock Lee con 15 o más fichas de Poder en una partida" },
  { id: 'itachi-power-15', level: 4, target: 1, hook: 'character.power.threshold', predicate: { name: 'ITACHI UCHIWA', threshold: 15 }, scope: 'match',
    text_fr: "avoir un Itachi à 15 Puissance ou plus en une partie",
    text_en: "have an Itachi with 15 or more Power in one match",
    text_pt: "tenha um Itachi com 15 ou mais de Poder em uma partida",
    text_it: "abbi un Itachi con 15 o più Potenza in una partita",
    text_pl: "miej Itachiego z 15 lub więcej Siły w jednym meczu",
    text_ja: "1回の対戦でうちはイタチをパワー15以上にする",
    text_es: "ten un Itachi con 15 o más de Poder en una partida" },
  { id: 'gaara-tokens-15', level: 4, target: 1, hook: 'character.power_tokens.threshold', predicate: { name: 'GAARA', threshold: 15 }, scope: 'match',
    text_fr: "avoir un Gaara avec 15 jetons de Puissance ou plus en une partie",
    text_en: "have a Gaara with 15 or more Power tokens in one match",
    text_pt: "tenha um Gaara com 15 ou mais fichas de Poder em uma partida",
    text_it: "abbi un Gaara con 15 o più token Potenza in una partita",
    text_pl: "miej Gaarę z 15 lub więcej żetonami Siły w jednym meczu",
    text_ja: "1回の対戦で我愛羅にパワートークンを15個以上持たせる",
    text_es: "ten un Gaara con 15 o más fichas de Poder en una partida" },
  { id: 'reveal-50', level: 4, target: 50, hook: 'character.revealed', scope: 'cumulative',
    text_fr: "révéler 50 personnages cachés au total",
    text_en: "reveal 50 hidden characters in total",
    text_pt: "revele 50 personagens ocultos no total",
    text_it: "rivela 50 personaggi nascosti in totale",
    text_pl: "odkryj 50 ukrytych postaci łącznie",
    text_ja: "伏せキャラクターを合計50体表にする",
    text_es: "revela a 50 personajes ocultos en total" },
  { id: 'reveal-ambush-50', level: 4, target: 50, hook: 'ambush.activated.via_reveal', scope: 'cumulative',
    text_fr: "révéler une carte cachée pour activer son AMBUSH 50 fois au total",
    text_en: "reveal a hidden card to trigger its AMBUSH 50 times in total",
    text_pt: "revele uma carta oculta para ativar seu AMBUSH 50 vezes no total",
    text_it: "rivela una carta nascosta per attivare il suo AMBUSH 50 volte in totale",
    text_pl: "odkryj ukrytą kartę, aby aktywować jej AMBUSH 50 razy łącznie",
    text_ja: "伏せカードを表にしてAMBUSHを合計50回発動する",
    text_es: "revela una carta oculta para activar su AMBUSH 50 veces en total" },

  { id: 'trade-complete-1', level: 1, target: 1, hook: 'trade.completed', scope: 'cumulative',
    text_fr: "réaliser un échange avec un ami",
    text_en: "complete a trade with a friend",
    text_pt: "conclua uma troca com um amigo",
    text_it: "completa uno scambio con un amico",
    text_pl: "sfinalizuj wymianę ze znajomym",
    text_ja: "フレンドとトレードを1回成立させる",
    text_es: "completa un intercambio con un amigo" },
  { id: 'trade-complete-5', level: 2, target: 5, hook: 'trade.completed', scope: 'cumulative',
    text_fr: "réaliser 5 échanges au total",
    text_en: "complete 5 trades in total",
    text_pt: "conclua 5 trocas no total",
    text_it: "completa 5 scambi in totale",
    text_pl: "sfinalizuj 5 wymian łącznie",
    text_ja: "トレードを合計5回成立させる",
    text_es: "completa 5 intercambios en total" },
  { id: 'trade-cards-10', level: 3, target: 10, hook: 'trade.cards.traded', scope: 'cumulative',
    text_fr: "échanger 10 cartes au total",
    text_en: "trade 10 cards in total",
    text_pt: "troque 10 cartas no total",
    text_it: "scambia 10 carte in totale",
    text_pl: "wymień 10 kart łącznie",
    text_ja: "カードを合計10枚トレードする",
    text_es: "intercambia 10 cartas en total" },
];

export const QUESTS_BY_ID: Record<string, Quest> = Object.fromEntries(QUESTS.map((q) => [q.id, q]));

export function getQuestById(id: string): Quest | undefined {
  return QUESTS_BY_ID[id];
}

export function getQuestsByLevel(level: QuestLevel): Quest[] {
  return QUESTS.filter((q) => q.level === level);
}

export function getQuestsByHook(hook: string): Quest[] {
  return QUESTS.filter((q) => q.hook === hook);
}
