import { registerMinato122Handlers } from './minato122';
import { registerSet2Handlers } from './set2';
import { registerTemari049Handlers } from './temari049';
import { registerSandVillageHandlers } from './sandVillage';
import { registerShinobiHandlers } from './shinobi';
import { registerKimimaro031Handlers } from './kimimaro031';
import { registerLegendaryGoldHandlers } from './legendaryGold';
import { registerItachi053Handlers } from './itachi053';
import { registerKakashi008Handlers } from './kakashi008';
import { registerJirobo032Handlers } from './jirobo032';
import { registerJirobo033Handlers } from './jirobo033';
import { registerZaku042Handlers } from './zaku042';
import { registerSakon036Handlers } from './sakon036';
import { registerKyubi006Handlers } from './kyubi006';
import { registerTsunade002Handlers } from './tsunade002';
import { registerSenbonRamenHandlers } from './senbonRamen';
import { registerNaruto005Handlers } from './naruto005';
import { registerRegionalChampionshipHandlers } from './regionalChampionship';
import { registerShikamaru118Handlers } from './shikamaru118';
import { registerSecretVariantHandlers } from './secretVariants';
import { registerIno124Handlers } from './ino124';
import { registerKin043Handlers } from './kin043';
import { registerKin044Handlers } from './kin044';
import { registerSSMissionHandlers } from './missions/ssMissionHandlers';
import { registerSoundMoveHandlers } from './soundMoves';
import { registerSnakeSword101Handlers } from './snakeSword101';
import { registerKabuto030Handlers } from './kabuto030';
import { registerDosu045Handlers } from './dosu045';
import { registerSakon037Handlers } from './sakon037';
import { registerKidomaru035Handlers } from './kidomaru035';
import { registerOrochimaru130Handlers } from './orochimaru130';

export function registerAllSSHandlers(): void {
  registerMinato122Handlers();
  registerSet2Handlers();
  registerTemari049Handlers();
  registerSandVillageHandlers();
  registerShinobiHandlers();
  registerKimimaro031Handlers();
  registerLegendaryGoldHandlers();
  registerItachi053Handlers();
  registerKakashi008Handlers();
  registerJirobo032Handlers();
  registerJirobo033Handlers();
  registerZaku042Handlers();
  registerSakon036Handlers();
  registerKyubi006Handlers();
  registerTsunade002Handlers();
  registerSenbonRamenHandlers();
  registerNaruto005Handlers();
  registerRegionalChampionshipHandlers();
  registerShikamaru118Handlers();
  registerSecretVariantHandlers();
  registerIno124Handlers();
  registerKin043Handlers();
  registerKin044Handlers();
  registerSSMissionHandlers();
  registerSoundMoveHandlers();
  registerSnakeSword101Handlers();
  registerKabuto030Handlers();
  registerDosu045Handlers();
  registerSakon037Handlers();
  registerKidomaru035Handlers();
  registerOrochimaru130Handlers();
}
